In [6]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

df=pd.read_csv("data/Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
ages = df['Age'].dropna().to_numpy()
print(ages)

[22.   38.   26.   35.   35.   54.    2.   27.   14.    4.   58.   20.
 39.   14.   55.    2.   31.   35.   34.   15.   28.    8.   38.   19.
 40.   66.   28.   42.   21.   18.   14.   40.   27.    3.   19.   18.
  7.   21.   49.   29.   65.   21.   28.5   5.   11.   22.   38.   45.
  4.   29.   19.   17.   26.   32.   16.   21.   26.   32.   25.    0.83
 30.   22.   29.   28.   17.   33.   16.   23.   24.   29.   20.   46.
 26.   59.   71.   23.   34.   34.   28.   21.   33.   37.   28.   21.
 38.   47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.   21.
 32.5  32.5  54.   12.   24.   45.   33.   20.   47.   29.   25.   23.
 19.   37.   16.   24.   22.   24.   19.   18.   19.   27.    9.   36.5
 42.   51.   22.   55.5  40.5  51.   16.   30.   44.   40.   26.   17.
  1.    9.   45.   28.   61.    4.    1.   21.   56.   18.   50.   30.
 36.    9.    1.    4.   45.   40.   36.   32.   19.   19.    3.   44.
 58.   42.   24.   28.   34.   45.5  18.    2.   32.   26.   16.   40.
 24.   35.   22.   30.   31.   27.   42.   32.   30.   16.   27.   51.
 38.   22.   19.   20.5  18.   35.   29.   59.    5.   24.   44.    8.
 19.   33.   29.   22.   30.   44.   25.   24.   37.   54.   29.   62.
 30.   41.   29.   30.   35.   50.    3.   52.   40.   36.   16.   25.
 58.   35.   25.   41.   37.   63.   45.    7.   35.   65.   28.   16.
 19.   33.   30.   22.   42.   22.   26.   19.   36.   24.   24.   23.5
  2.   50.   19.    0.92 17.   30.   30.   24.   18.   26.   28.   43.
 26.   24.   54.   31.   40.   22.   27.   30.   22.   36.   61.   36.
 31.   16.   45.5  38.   16.   29.   41.   45.   45.    2.   24.   28.
 25.   36.   24.   40.    3.   42.   23.   15.   25.   28.   22.   38.
 40.   29.   45.   35.   30.   60.   24.   25.   18.   19.   22.    3.
 22.   27.   20.   19.   42.    1.   32.   35.   18.    1.   36.   17.
 36.   21.   28.   23.   24.   22.   31.   46.   23.   28.   39.   26.
 21.   28.   20.   34.   51.    3.   21.   33.   44.   34.   18.   30.
 10.   21.   29.   28.   18.   28.   19.   32.   28.   42.   17.   50.
 14.   21.   24.   64.   31.   45.   20.   25.   28.    4.   13.   34.
  5.   52.   36.   30.   49.   29.   65.   50.   48.   34.   47.   48.
 38.   56.    0.75 38.   33.   23.   22.   34.   29.   22.    2.    9.
 50.   63.   25.   35.   58.   30.    9.   21.   55.   71.   21.   54.
 25.   24.   17.   21.   37.   16.   18.   33.   28.   26.   29.   36.
 54.   24.   47.   34.   36.   32.   30.   22.   44.   40.5  50.   39.
 23.    2.   17.   30.    7.   45.   30.   22.   36.    9.   11.   32.
 50.   64.   19.   33.    8.   17.   27.   22.   22.   62.   48.   39.
 36.   40.   28.   24.   19.   29.   32.   62.   53.   36.   16.   19.
 34.   39.   32.   25.   39.   54.   36.   18.   47.   60.   22.   35.
 52.   47.   37.   36.   49.   49.   24.   44.   35.   36.   30.   27.
 22.   40.   39.   35.   24.   34.   26.    4.   26.   27.   42.   20.
 21.   21.   61.   57.   21.   26.   80.   51.   32.    9.   28.   32.
 31.   41.   20.   24.    2.    0.75 48.   19.   56.   23.   18.   21.
 18.   24.   32.   23.   58.   50.   40.   47.   36.   20.   32.   25.
 43.   40.   31.   70.   31.   18.   24.5  18.   43.   36.   27.   20.
 14.   60.   25.   14.   19.   18.   15.   31.    4.   25.   60.   52.
 44.   49.   42.   18.   35.   18.   25.   26.   39.   45.   42.   22.
 24.   48.   29.   52.   19.   38.   27.   33.    6.   17.   34.   50.
 27.   20.   30.   25.   25.   29.   11.   23.   23.   28.5  48.   35.
 36.   21.   24.   31.   70.   16.   30.   19.   31.    4.    6.   33.
 23.   48.    0.67 28.   18.   34.   33.   41.   20.   36.   16.   51.
 30.5  32.   24.   48.   57.   54.   18.    5.   43.   13.   17.   29.
 25.   25.   18.    8.    1.   46.   16.   25.   39.   49.   31.   30.
 30.   34.   31.   11.    0.42 27.   31.   39.   18.   39.   33.   26.
 39.   35.    6.   30.5  23.   31.   43.   10.   52.   27.   38.   27.
  2.    1.   62.   15.    0.83 23.   18.   39.   21.   32.   20.   16.
 30.   34.5  17.   42.   35.   28.    4.   74.    9.   16.   44.   18.
 45.   51.   24.   41.   21.   48.   24.   42.   27.   31.    4.   26.
 47.   33.   47.   28.   15.   20.   19.   56.   25.   33.   22.   28.
 25.   39.   27.   19.   26.   32.  ]

In [28]:
ages.shape

(714,)

In [29]:

ages.dtype

dtype('float64')

In [30]:

ages.size

714

In [9]:
fares = df['Fare'].to_numpy()
print(fares)

[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
   8.05     9.825   14.4583   7.925    7.75    21.     247.5208  31.275
  73.5      8.05    30.0708  13.      77.2875  11.2417   7.75     7.1417
  22.3583   6.975    7.8958   7.05    14.5     26.      13.      15.0458
  26.2833  53.1      9.2167  79.2     15.2458   7.75    15.85     6.75
  11.5     36.75     7.7958  34.375   26.      13.      12.525   66.6
   8.05    14.5      7.3125  61.3792   7.7333   8.05     8.6625  69.55
  16.1     15.75     7.775    8.6625  39.6875  20.525   55.      27.9
  25.925   56.4958  33.5     29.125   11.1333   7.925   30.6958   7.8542
  25.4667  28.7125  13.       0.      69.55    15.05    31.3875  39.
  22.025   50.      15.5     26.55    15.5      7.8958  13.      13.
   7.8542  26.      27.7208 146.5208   7.75     8.4042   7.75    13.
   9.5     69.55     6.4958   7.225    8.05    10.4625  15.85    18.7875
   7.75    31.       7.05    21.       7.25    13.       7.75   113.275
   7.925   27.      76.2917  10.5      8.05    13.       8.05     7.8958
  90.       9.35    10.5      7.25    13.      25.4667  83.475    7.775
  13.5     31.3875  10.5      7.55    26.      26.25    10.5     12.275
  14.4542  15.5     10.5      7.125    7.225   90.       7.775   14.5
  52.5542  26.       7.25    10.4625  26.55    16.1     20.2125  15.2458
  79.2     86.5    512.3292  26.       7.75    31.3875  79.65     0.
   7.75    10.5     39.6875   7.775  153.4625 135.6333  31.       0.
  19.5     29.7      7.75    77.9583   7.75     0.      29.125   20.25
   7.75     7.8542   9.5      8.05    26.       8.6625   9.5      7.8958
  13.       7.75    78.85    91.0792  12.875    8.85     7.8958  27.7208
   7.2292 151.55    30.5    247.5208   7.75    23.25     0.      12.35
   8.05   151.55   110.8833 108.9     24.      56.9292  83.1583 262.375
  26.       7.8958  26.25     7.8542  26.      14.     164.8667 134.5
   7.25     7.8958  12.35    29.      69.55   135.6333   6.2375  13.
  20.525   57.9792  23.25    28.5    153.4625  18.     133.65     7.8958
  66.6    134.5      8.05    35.5     26.     263.      13.      13.
  13.      13.      13.      16.1     15.9      8.6625   9.225   35.
   7.2292  17.8      7.225    9.5     55.      13.       7.8792   7.8792
  27.9     27.7208  14.4542   7.05    15.5      7.25    75.25     7.2292
   7.75    69.3     55.4417   6.4958   8.05   135.6333  21.075   82.1708
   7.25   211.5      4.0125   7.775  227.525   15.7417   7.925   52.
   7.8958  73.5     46.9     13.       7.7292  12.     120.       7.7958
   7.925  113.275   16.7      7.7958   7.8542  26.      10.5     12.65
   7.925    8.05     9.825   15.85     8.6625  21.       7.75    18.75
   7.775   25.4667   7.8958   6.8583  90.       0.       7.925    8.05
  32.5     13.      13.      24.15     7.8958   7.7333   7.875   14.4
  20.2125   7.25    26.      26.       7.75     8.05    26.55    16.1
  26.       7.125   55.9    120.      34.375   18.75   263.      10.5
  26.25     9.5      7.775   13.       8.1125  81.8583  19.5     26.55
  19.2583  30.5     27.75    19.9667  27.75    89.1042   8.05     7.8958
  26.55    51.8625  10.5      7.75    26.55     8.05    38.5     13.
   8.05     7.05     0.      26.55     7.725   19.2583   7.25     8.6625
  27.75    13.7917   9.8375  52.      21.       7.0458   7.5208  12.2875
  46.9      0.       8.05     9.5875  91.0792  25.4667  90.      29.7
   8.05    15.9     19.9667   7.25    30.5     49.5042   8.05    14.4583
  78.2667  15.1    151.55     7.7958   8.6625   7.75     7.6292   9.5875
  86.5    108.9     26.      26.55    22.525   56.4958   7.75     8.05
  26.2875  59.4      7.4958  34.0208  10.5     24.15    26.       7.8958
  93.5      7.8958   7.225   57.9792   7.2292   7.75    10.5    221.7792
   7.925   11.5     26.       7.2292   7.2292  22.3583   8.6625  26.25
  26.55   106.425   14.5     49.5     71.      31.275   31.275   26.
 106.425   26.      26.      13.8625  20.525   36.75   110.8833  26.
   7.8292   7.225    7.775   26.55    39.6    227.525   79.65    17.4
   7.75     7.8958  13.5      8.05     8.05    24.15     7.8958  21.075
   7.2292   7.8542  10.5     51.4792  26.3875   7.75     8.05    14.5
  13.      55.9     14.4583   7.925   30.     110.8833  26.      40.125
   8.7125  79.65    15.      79.2      8.05     8.05     7.125   78.2667
   7.25     7.75    26.      24.15    33.       0.       7.225   56.9292
  27.       7.8958  42.4      8.05    26.55    15.55     7.8958  30.5
  41.5792 153.4625  31.275    7.05    15.5      7.75     8.05    65.
  14.4     16.1     39.      10.5     14.4542  52.5542  15.7417   7.8542
  16.1     32.3208  12.35    77.9583   7.8958   7.7333  30.       7.0542
  30.5      0.      27.9     13.       7.925   26.25    39.6875  16.1
   7.8542  69.3     27.9     56.4958  19.2583  76.7292   7.8958  35.5
   7.55     7.55     7.8958  23.       8.4333   7.8292   6.75    73.5
   7.8958  15.5     13.     113.275  133.65     7.225   25.5875   7.4958
   7.925   73.5     13.       7.775    8.05    52.      39.      52.
  10.5     13.       0.       7.775    8.05     9.8417  46.9    512.3292
   8.1375  76.7292   9.225   46.9     39.      41.5792  39.6875  10.1708
   7.7958 211.3375  57.      13.4167  56.4958   7.225   26.55    13.5
   8.05     7.7333 110.8833   7.65   227.525   26.2875  14.4542   7.7417
   7.8542  26.      13.5     26.2875 151.55    15.2458  49.5042  26.55
  52.       9.4833  13.       7.65   227.525   10.5     15.5      7.775
  33.       7.0542  13.      13.      53.1      8.6625  21.       7.7375
  26.       7.925  211.3375  18.7875   0.      13.      13.      16.1
  34.375  512.3292   7.8958   7.8958  30.      78.85   262.375   16.1
   7.925   71.      20.25    13.      53.1      7.75    23.      12.475
   9.5      7.8958  65.      14.5      7.7958  11.5      8.05    86.5
  14.5      7.125    7.2292 120.       7.775   77.9583  39.6      7.75
  24.15     8.3625   9.5      7.8542  10.5      7.225   23.       7.75
   7.75    12.475    7.7375 211.3375   7.2292  57.      30.      23.45
   7.05     7.25     7.4958  29.125   20.575   79.2      7.75    26.
  69.55    30.6958   7.8958  13.      25.9292   8.6833   7.2292  24.15
  13.      26.25   120.       8.5167   6.975    7.775    0.       7.775
  13.      53.1      7.8875  24.15    10.5     31.275    8.05     0.
   7.925   37.0042   6.45    27.9     93.5      8.6625   0.      12.475
  39.6875   6.95    56.4958  37.0042   7.75    80.      14.4542  18.75
   7.2292   7.8542   8.3     83.1583   8.6625   8.05    56.4958  29.7
   7.925   10.5     31.       6.4375   8.6625   7.55    69.55     7.8958
  33.      89.1042  31.275    7.775   15.2458  39.4     26.       9.35
 164.8667  26.55    19.2583   7.2292  14.1083  11.5     25.9292  69.55
  13.      13.      13.8583  50.4958   9.5     11.1333   7.8958  52.5542
   5.       9.      24.       7.225    9.8458   7.8958   7.8958  83.1583
  26.       7.8958  10.5167  10.5      7.05    29.125   13.      30.
  23.45    30.       7.75  ]

In [50]:
rupee = fares *86
print(rupee)

[  623.5     6130.3638   681.55    4566.6      692.3      727.4138
  4460.175   1812.45     957.4638  2586.0888  1436.2     2283.3
   692.3     2689.65     675.4612  1376.      2504.75    1118.
  1548.       621.35    2236.      1118.       690.5112  3053.
  1812.45    2699.325    621.35   22618.       677.6112   679.0388
  2383.9888 12600.7888   666.5      903.      7066.6888  4472.
   621.7112   692.3     1548.       966.7862   814.85    1806.
   679.0388  3575.8112   677.6112   692.3     1333.       666.5
  1864.4112  1530.8     3413.125    670.8     6598.7112  2236.
  5330.2112  3053.       903.       621.7112  2386.5     4033.4
   621.7112  6880.      7178.85    2399.4     2383.9888  1311.1388
   903.       701.6138   681.55     744.975    903.      4033.4
  6321.      1243.0612  4858.6388   657.9      679.0388   692.3
  2494.      1072.85     774.       817.       669.725   4050.6
   903.      1363.1     2956.25     692.3    22618.       692.3
   692.3      675.4612  5261.05    1769.45     623.5      692.3
  2980.2612  5448.8138  1978.      2236.       679.0388   679.0388
  6646.725    744.2612   681.55     679.0388   657.9      668.65
   679.0388  2076.9     4472.      1243.0612   692.3      844.95
  1243.4138   681.55     666.5     1806.     21286.7888  2689.65
  6321.       692.3     2586.0888  1118.      6646.725    966.7862
   666.5      614.1862  1922.8138   599.85     679.0388   606.3
  1247.      2236.      1118.      1293.9388  2260.3638  4566.6
   792.6362  6811.2     1311.1388   666.5     1363.1      580.5
   989.      3160.5      670.4388  2956.25    2236.      1118.
  1077.15    5727.6      692.3     1247.       628.875   5278.6112
   665.0638   692.3      744.975   5981.3     1384.6     1354.5
   668.65     744.975   3413.125   1765.15    4730.      2399.4
  2229.55    4858.6388  2881.      2504.75     957.4638   681.55
  2639.8388   675.4612  2190.1362  2469.275   1118.         0.
  5981.3     1294.3     2699.325   3354.      1894.15    4300.
  1333.      2283.3     1333.       679.0388  1118.      1118.
   675.4612  2236.      2383.9888 12600.7888   666.5      722.7612
   666.5     1118.       817.      5981.3      558.6388   621.35
   692.3      899.775   1363.1     1615.725    666.5     2666.
   606.3     1806.       623.5     1118.       666.5     9741.65
   681.55    2322.      6561.0862   903.       692.3     1118.
   692.3      679.0388  7740.       804.1      903.       623.5
  1118.      2190.1362  7178.85     668.65    1161.      2699.325
   903.       649.3     2236.      2257.5      903.      1055.65
  1243.0612  1333.       903.       612.75     621.35    7740.
   668.65    1247.      4519.6612  2236.       623.5      899.775
  2283.3     1384.6     1738.275   1311.1388  6811.2     7439.
 44060.3112  2236.       666.5     2699.325   6849.9        0.
   666.5      903.      3413.125    668.65   13197.775  11664.4638
  2666.         0.      1677.      2554.2      666.5     6704.4138
   666.5        0.      2504.75    1741.5      666.5      675.4612
   817.       692.3     2236.       744.975    817.       679.0388
  1118.       666.5     6781.1     7832.8112  1107.25     761.1
   679.0388  2383.9888   621.7112 13033.3     2623.     21286.7888
   666.5     1999.5        0.      1062.1      692.3    13033.3
  9535.9638  9365.4     2064.      4895.9112  7151.6138 22564.25
  2236.       679.0388  2257.5      675.4612  2236.      1204.
 14178.5362 11567.       623.5      679.0388  1062.1     2494.
  5981.3    11664.4638   536.425   1118.      1765.15    4986.2112
  1999.5     2451.     13197.775   1548.     11493.9      679.0388
  5727.6    11567.       692.3     3053.      2236.     22618.
  1118.      1118.      1118.      1118.      1118.      1384.6
  1367.4      744.975    793.35    3010.       621.7112  1530.8
   621.35     817.      4730.      1118.       677.6112   677.6112
  2399.4     2383.9888  1243.0612   606.3     1333.       623.5
  6471.5      621.7112   666.5     5959.8     4767.9862   558.6388
   692.3    11664.4638  1812.45    7066.6888   623.5    18189.
   345.075    668.65   19567.15    1353.7862   681.55    4472.
   679.0388  6321.      4033.4     1118.       664.7112  1032.
 10320.       670.4388   681.55    9741.65    1436.2      670.4388
   675.4612  2236.       903.      1087.9      681.55     692.3
   844.95    1363.1      744.975   1806.       666.5     1612.5
   668.65    2190.1362   679.0388   589.8138  7740.         0.
   681.55     692.3     2795.      1118.      1118.      2076.9
   679.0388   665.0638   677.25    1238.4     1738.275    623.5
  2236.      2236.       666.5      692.3     2283.3     1384.6
  2236.       612.75    4807.4    10320.      2956.25    1612.5
 22618.       903.      2257.5      817.       668.65    1118.
   697.675   7039.8138  1677.      2283.3     1656.2138  2623.
  2386.5     1717.1362  2386.5     7662.9612   692.3      679.0388
  2283.3     4460.175    903.       666.5     2283.3      692.3
  3311.      1118.       692.3      606.3        0.      2283.3
   664.35    1656.2138   623.5      744.975   2386.5     1186.0862
   846.025   4472.      1806.       605.9388   646.7888  1056.725
  4033.4        0.       692.3      824.525   7832.8112  2190.1362
  7740.      2554.2      692.3     1367.4     1717.1362   623.5
  2623.      4257.3612   692.3     1243.4138  6730.9362  1298.6
 13033.3      670.4388   744.975    666.5      656.1112   824.525
  7439.      9365.4     2236.      2283.3     1937.15    4858.6388
   666.5      692.3     2260.725   5108.4      644.6388  2925.7888
   903.      2076.9     2236.       679.0388  8041.       679.0388
   621.35    4986.2112   621.7112   666.5      903.     19073.0112
   681.55     989.      2236.       621.7112   621.7112  1922.8138
   744.975   2257.5     2283.3     9152.55    1247.      4257.
  6106.      2689.65    2689.65    2236.      9152.55    2236.
  2236.      1192.175   1765.15    3160.5     9535.9638  2236.
   673.3112   621.35     668.65    2283.3     3405.6    19567.15
  6849.9     1496.4      666.5      679.0388  1161.       692.3
   692.3     2076.9      679.0388  1812.45     621.7112   675.4612
   903.      4427.2112  2269.325    666.5      692.3     1247.
  1118.      4807.4     1243.4138   681.55    2580.      9535.9638
  2236.      3450.75     749.275   6849.9     1290.      6811.2
   692.3      692.3      612.75    6730.9362   623.5      666.5
  2236.      2076.9     2838.         0.       621.35    4895.9112
  2322.       679.0388  3646.4      692.3     2283.3     1337.3
   679.0388  2623.      3575.8112 13197.775   2689.65     606.3
  1333.       666.5      692.3     5590.      1238.4     1384.6
  3354.       903.      1243.0612  4519.6612  1353.7862   675.4612
  1384.6     2779.5888  1062.1     6704.4138   679.0388   665.0638
  2580.       606.6612  2623.         0.      2399.4     1118.
   681.55    2257.5     3413.125   1384.6      675.4612  5959.8
  2399.4     4858.6388  1656.2138  6598.7112   679.0388  3053.
   649.3      649.3      679.0388  1978.       725.2638   673.3112
   580.5     6321.       679.0388  1333.      1118.      9741.65
 11493.9      621.35    2200.525    644.6388   681.55    6321.
  1118.       668.65     692.3     4472.      3354.      4472.
   903.      1118.         0.       668.65     692.3      846.3862
  4033.4    44060.3112   699.825   6598.7112   793.35    4033.4
  3354.      3575.8112  3413.125    874.6888   670.4388 18175.025
  4902.      1153.8362  4858.6388   621.35    2283.3     1161.
   692.3      665.0638  9535.9638   657.9    19567.15    2260.725
  1243.0612   665.7862   675.4612  2236.      1161.      2260.725
 13033.3     1311.1388  4257.3612  2283.3     4472.       815.5638
  1118.       657.9    19567.15     903.      1333.       668.65
  2838.       606.6612  1118.      1118.      4566.6      744.975
  1806.       665.425   2236.       681.55   18175.025   1615.725
     0.      1118.      1118.      1384.6     2956.25   44060.3112
   679.0388   679.0388  2580.      6781.1    22564.25    1384.6
   681.55    6106.      1741.5     1118.      4566.6      666.5
  1978.      1072.85     817.       679.0388  5590.      1247.
   670.4388   989.       692.3     7439.      1247.       612.75
   621.7112 10320.       668.65    6704.4138  3405.6      666.5
  2076.9      719.175    817.       675.4612   903.       621.35
  1978.       666.5      666.5     1072.85     665.425  18175.025
   621.7112  4902.      2580.      2016.7      606.3      623.5
   644.6388  2504.75    1769.45    6811.2      666.5     2236.
  5981.3     2639.8388   679.0388  1118.      2229.9112   746.7638
   621.7112  2076.9     1118.      2257.5    10320.       732.4362
   599.85     668.65       0.       668.65    1118.      4566.6
   678.325   2076.9      903.      2689.65     692.3        0.
   681.55    3182.3612   554.7     2399.4     8041.       744.975
     0.      1072.85    3413.125    597.7     4858.6388  3182.3612
   666.5     6880.      1243.0612  1612.5      621.7112   675.4612
   713.8     7151.6138   744.975    692.3     4858.6388  2554.2
   681.55     903.      2666.       553.625    744.975    649.3
  5981.3      679.0388  2838.      7662.9612  2689.65     668.65
  1311.1388  3388.4     2236.       804.1    14178.5362  2283.3
  1656.2138   621.7112  1213.3138   989.      2229.9112  5981.3
  1118.      1118.      1191.8138  4342.6388   817.       957.4638
   679.0388  4519.6612   430.       774.      2064.       621.35
   846.7388   679.0388   679.0388  7151.6138  2236.       679.0388
   904.4362   903.       606.3     2504.75    1118.      2580.
  2016.7     2580.       666.5   ]

In [49]:
new=fares *1.10
print(new)

[  7.975    78.41163   8.7175   58.41      8.855     9.30413  57.04875
  23.1825   12.24663  33.07788  18.37     29.205     8.855    34.4025
   8.63962  17.6      32.0375   14.3      19.8       7.9475   28.6
  14.3       8.83212  39.05     23.1825   34.52625   7.9475  289.3
   8.66712   8.68538  30.49288 161.17288   8.525    11.55     90.38788
  57.2       7.95212   8.855    19.8      12.36587  10.4225   23.1
   8.68538  45.73712   8.66712   8.855    17.05      8.525    23.84712
  19.58     43.65625   8.58     84.40212  28.6      68.17712  39.05
  11.55      7.95212  30.525    51.59      7.95212  88.       91.8225
  30.69     30.49288  16.77038  11.55      8.97413   8.7175    9.52875
  11.55     51.59     80.85     15.89962  62.14538   8.415     8.68538
   8.855    31.9      13.7225    9.9      10.45      8.56625  51.81
  11.55     17.435    37.8125    8.855   289.3       8.855     8.855
   8.63962  67.2925   22.6325    7.975     8.855    38.11962  69.69413
  25.3      28.6       8.68538   8.68538  85.01625   9.51962   8.7175
   8.68538   8.415     8.5525    8.68538  26.565    57.2      15.89962
   8.855    10.8075   15.90413   8.7175    8.525    23.1     272.27288
  34.4025   80.85      8.855    33.07788  14.3      85.01625  12.36587
   8.525     7.85587  24.59413   7.6725    8.68538   7.755    15.95
  28.6      14.3      16.55038  28.91163  58.41     10.13837  87.12
  16.77038   8.525    17.435     7.425    12.65     40.425     8.57538
  37.8125   28.6      14.3      13.7775   73.26      8.855    15.95
   8.04375  67.51712   8.50663   8.855     9.52875  76.505    17.71
  17.325     8.5525    9.52875  43.65625  22.5775   60.5      30.69
  28.5175   62.14538  36.85     32.0375   12.24663   8.7175   33.76538
   8.63962  28.01337  31.58375  14.3       0.       76.505    16.555
  34.52625  42.9      24.2275   55.       17.05     29.205    17.05
   8.68538  14.3      14.3       8.63962  28.6      30.49288 161.17288
   8.525     9.24462   8.525    14.3      10.45     76.505     7.14538
   7.9475    8.855    11.50875  17.435    20.66625   8.525    34.1
   7.755    23.1       7.975    14.3       8.525   124.6025    8.7175
  29.7      83.92087  11.55      8.855    14.3       8.855     8.68538
  99.       10.285    11.55      7.975    14.3      28.01337  91.8225
   8.5525   14.85     34.52625  11.55      8.305    28.6      28.875
  11.55     13.5025   15.89962  17.05     11.55      7.8375    7.9475
  99.        8.5525   15.95     57.80962  28.6       7.975    11.50875
  29.205    17.71     22.23375  16.77038  87.12     95.15    563.56212
  28.6       8.525    34.52625  87.615     0.        8.525    11.55
  43.65625   8.5525  168.80875 149.19663  34.1       0.       21.45
  32.67      8.525    85.75413   8.525     0.       32.0375   22.275
   8.525     8.63962  10.45      8.855    28.6       9.52875  10.45
   8.68538  14.3       8.525    86.735   100.18712  14.1625    9.735
   8.68538  30.49288   7.95212 166.705    33.55    272.27288   8.525
  25.575     0.       13.585     8.855   166.705   121.97163 119.79
  26.4      62.62212  91.47413 288.6125   28.6       8.68538  28.875
   8.63962  28.6      15.4     181.35337 147.95      7.975     8.68538
  13.585    31.9      76.505   149.19663   6.86125  14.3      22.5775
  63.77712  25.575    31.35    168.80875  19.8     147.015     8.68538
  73.26    147.95      8.855    39.05     28.6     289.3      14.3
  14.3      14.3      14.3      14.3      17.71     17.49      9.52875
  10.1475   38.5       7.95212  19.58      7.9475   10.45     60.5
  14.3       8.66712   8.66712  30.69     30.49288  15.89962   7.755
  17.05      7.975    82.775     7.95212   8.525    76.23     60.98587
   7.14538   8.855   149.19663  23.1825   90.38788   7.975   232.65
   4.41375   8.5525  250.2775   17.31587   8.7175   57.2       8.68538
  80.85     51.59     14.3       8.50212  13.2     132.        8.57538
   8.7175  124.6025   18.37      8.57538   8.63962  28.6      11.55
  13.915     8.7175    8.855    10.8075   17.435     9.52875  23.1
   8.525    20.625     8.5525   28.01337   8.68538   7.54413  99.
   0.        8.7175    8.855    35.75     14.3      14.3      26.565
   8.68538   8.50663   8.6625   15.84     22.23375   7.975    28.6
  28.6       8.525     8.855    29.205    17.71     28.6       7.8375
  61.49    132.       37.8125   20.625   289.3      11.55     28.875
  10.45      8.5525   14.3       8.92375  90.04413  21.45     29.205
  21.18413  33.55     30.525    21.96337  30.525    98.01462   8.855
   8.68538  29.205    57.04875  11.55      8.525    29.205     8.855
  42.35     14.3       8.855     7.755     0.       29.205     8.4975
  21.18413   7.975     9.52875  30.525    15.17087  10.82125  57.2
  23.1       7.75038   8.27288  13.51625  51.59      0.        8.855
  10.54625 100.18712  28.01337  99.       32.67      8.855    17.49
  21.96337   7.975    33.55     54.45462   8.855    15.90413  86.09337
  16.61    166.705     8.57538   9.52875   8.525     8.39212  10.54625
  95.15    119.79     28.6      29.205    24.7775   62.14538   8.525
   8.855    28.91625  65.34      8.24538  37.42288  11.55     26.565
  28.6       8.68538 102.85      8.68538   7.9475   63.77712   7.95212
   8.525    11.55    243.95712   8.7175   12.65     28.6       7.95212
   7.95212  24.59413   9.52875  28.875    29.205   117.0675   15.95
  54.45     78.1      34.4025   34.4025   28.6     117.0675   28.6
  28.6      15.24875  22.5775   40.425   121.97163  28.6       8.61212
   7.9475    8.5525   29.205    43.56    250.2775   87.615    19.14
   8.525     8.68538  14.85      8.855     8.855    26.565     8.68538
  23.1825    7.95212   8.63962  11.55     56.62712  29.02625   8.525
   8.855    15.95     14.3      61.49     15.90413   8.7175   33.
 121.97163  28.6      44.1375    9.58375  87.615    16.5      87.12
   8.855     8.855     7.8375   86.09337   7.975     8.525    28.6
  26.565    36.3       0.        7.9475   62.62212  29.7       8.68538
  46.64      8.855    29.205    17.105     8.68538  33.55     45.73712
 168.80875  34.4025    7.755    17.05      8.525     8.855    71.5
  15.84     17.71     42.9      11.55     15.89962  57.80962  17.31587
   8.63962  17.71     35.55288  13.585    85.75413   8.68538   8.50663
  33.        7.75962  33.55      0.       30.69     14.3       8.7175
  28.875    43.65625  17.71      8.63962  76.23     30.69     62.14538
  21.18413  84.40212   8.68538  39.05      8.305     8.305     8.68538
  25.3       9.27663   8.61212   7.425    80.85      8.68538  17.05
  14.3     124.6025  147.015     7.9475   28.14625   8.24538   8.7175
  80.85     14.3       8.5525    8.855    57.2      42.9      57.2
  11.55     14.3       0.        8.5525    8.855    10.82587  51.59
 563.56212   8.95125  84.40212  10.1475   51.59     42.9      45.73712
  43.65625  11.18788   8.57538 232.47125  62.7      14.75837  62.14538
   7.9475   29.205    14.85      8.855     8.50663 121.97163   8.415
 250.2775   28.91625  15.89962   8.51587   8.63962  28.6      14.85
  28.91625 166.705    16.77038  54.45462  29.205    57.2      10.43163
  14.3       8.415   250.2775   11.55     17.05      8.5525   36.3
   7.75962  14.3      14.3      58.41      9.52875  23.1       8.51125
  28.6       8.7175  232.47125  20.66625   0.       14.3      14.3
  17.71     37.8125  563.56212   8.68538   8.68538  33.       86.735
 288.6125   17.71      8.7175   78.1      22.275    14.3      58.41
   8.525    25.3      13.7225   10.45      8.68538  71.5      15.95
   8.57538  12.65      8.855    95.15     15.95      7.8375    7.95212
 132.        8.5525   85.75413  43.56      8.525    26.565     9.19875
  10.45      8.63962  11.55      7.9475   25.3       8.525     8.525
  13.7225    8.51125 232.47125   7.95212  62.7      33.       25.795
   7.755     7.975     8.24538  32.0375   22.6325   87.12      8.525
  28.6      76.505    33.76538   8.68538  14.3      28.52212   9.55163
   7.95212  26.565    14.3      28.875   132.        9.36837   7.6725
   8.5525    0.        8.5525   14.3      58.41      8.67625  26.565
  11.55     34.4025    8.855     0.        8.7175   40.70462   7.095
  30.69    102.85      9.52875   0.       13.7225   43.65625   7.645
  62.14538  40.70462   8.525    88.       15.89962  20.625     7.95212
   8.63962   9.13     91.47413   9.52875   8.855    62.14538  32.67
   8.7175   11.55     34.1       7.08125   9.52875   8.305    76.505
   8.68538  36.3      98.01462  34.4025    8.5525   16.77038  43.34
  28.6      10.285   181.35337  29.205    21.18413   7.95212  15.51913
  12.65     28.52212  76.505    14.3      14.3      15.24413  55.54538
  10.45     12.24663   8.68538  57.80962   5.5       9.9      26.4
   7.9475   10.83038   8.68538   8.68538  91.47413  28.6       8.68538
  11.56837  11.55      7.755    32.0375   14.3      33.       25.795
  33.        8.525  ]

In [10]:
np.mean(ages)

np.float64(29.69911764705882)

In [12]:
t=np.mean(ages)
print(t)

29.69911764705882

In [11]:
np.median(ages)

np.float64(28.0)

In [13]:
t=np.median(ages)
print(t)

28.0

In [14]:
np.min(ages)

np.float64(0.42)

In [15]:
t=np.min(ages)
print(t)

0.42

In [16]:
t=np.max(ages)
print(t)

80.0

In [17]:

t=np.min(fares)
print(t)

0.0

In [18]:
t=np.max(fares)
print(t)

512.3292

In [19]:
t=np.std(ages)
print(t)

14.516321150817316

In [21]:
t=np.var(ages)
print(t)

210.72357975366617

In [22]:
t=np.percentile(ages, 25)
print(t)

20.125

In [23]:
t=np.percentile(ages, 50)
print(t)

28.0

In [24]:
t=np.percentile(ages, 75)
print(t)

38.0

In [26]:

t=np.sum(df['Survived'])
print(t)

342

In [31]:
np.quantile(ages, 0.25)

np.float64(20.125)

In [32]:
t=np.quantile(ages, 0.5)
print(t)

28.0

In [34]:
t=np.quantile(ages, 0.75)
print(t)

38.0

In [35]:
np.square(ages)

array([4.84000e+02, 1.44400e+03, 6.76000e+02, 1.22500e+03, 1.22500e+03,
       2.91600e+03, 4.00000e+00, 7.29000e+02, 1.96000e+02, 1.60000e+01,
       3.36400e+03, 4.00000e+02, 1.52100e+03, 1.96000e+02, 3.02500e+03,
       4.00000e+00, 9.61000e+02, 1.22500e+03, 1.15600e+03, 2.25000e+02,
       7.84000e+02, 6.40000e+01, 1.44400e+03, 3.61000e+02, 1.60000e+03,
       4.35600e+03, 7.84000e+02, 1.76400e+03, 4.41000e+02, 3.24000e+02,
       1.96000e+02, 1.60000e+03, 7.29000e+02, 9.00000e+00, 3.61000e+02,
       3.24000e+02, 4.90000e+01, 4.41000e+02, 2.40100e+03, 8.41000e+02,
       4.22500e+03, 4.41000e+02, 8.12250e+02, 2.50000e+01, 1.21000e+02,
       4.84000e+02, 1.44400e+03, 2.02500e+03, 1.60000e+01, 8.41000e+02,
       3.61000e+02, 2.89000e+02, 6.76000e+02, 1.02400e+03, 2.56000e+02,
       4.41000e+02, 6.76000e+02, 1.02400e+03, 6.25000e+02, 6.88900e-01,
       9.00000e+02, 4.84000e+02, 8.41000e+02, 7.84000e+02, 2.89000e+02,
       1.08900e+03, 2.56000e+02, 5.29000e+02, 5.76000e+02, 8.41000e+02,
       4.00000e+02, 2.11600e+03, 6.76000e+02, 3.48100e+03, 5.04100e+03,
       5.29000e+02, 1.15600e+03, 1.15600e+03, 7.84000e+02, 4.41000e+02,
       1.08900e+03, 1.36900e+03, 7.84000e+02, 4.41000e+02, 1.44400e+03,
       2.20900e+03, 2.10250e+02, 4.84000e+02, 4.00000e+02, 2.89000e+02,
       4.41000e+02, 4.97025e+03, 8.41000e+02, 5.76000e+02, 4.00000e+00,
       4.41000e+02, 1.05625e+03, 1.05625e+03, 2.91600e+03, 1.44000e+02,
       5.76000e+02, 2.02500e+03, 1.08900e+03, 4.00000e+02, 2.20900e+03,
       8.41000e+02, 6.25000e+02, 5.29000e+02, 3.61000e+02, 1.36900e+03,
       2.56000e+02, 5.76000e+02, 4.84000e+02, 5.76000e+02, 3.61000e+02,
       3.24000e+02, 3.61000e+02, 7.29000e+02, 8.10000e+01, 1.33225e+03,
       1.76400e+03, 2.60100e+03, 4.84000e+02, 3.08025e+03, 1.64025e+03,
       2.60100e+03, 2.56000e+02, 9.00000e+02, 1.93600e+03, 1.60000e+03,
       6.76000e+02, 2.89000e+02, 1.00000e+00, 8.10000e+01, 2.02500e+03,
       7.84000e+02, 3.72100e+03, 1.60000e+01, 1.00000e+00, 4.41000e+02,
       3.13600e+03, 3.24000e+02, 2.50000e+03, 9.00000e+02, 1.29600e+03,
       8.10000e+01, 1.00000e+00, 1.60000e+01, 2.02500e+03, 1.60000e+03,
       1.29600e+03, 1.02400e+03, 3.61000e+02, 3.61000e+02, 9.00000e+00,
       1.93600e+03, 3.36400e+03, 1.76400e+03, 5.76000e+02, 7.84000e+02,
       1.15600e+03, 2.07025e+03, 3.24000e+02, 4.00000e+00, 1.02400e+03,
       6.76000e+02, 2.56000e+02, 1.60000e+03, 5.76000e+02, 1.22500e+03,
       4.84000e+02, 9.00000e+02, 9.61000e+02, 7.29000e+02, 1.76400e+03,
       1.02400e+03, 9.00000e+02, 2.56000e+02, 7.29000e+02, 2.60100e+03,
       1.44400e+03, 4.84000e+02, 3.61000e+02, 4.20250e+02, 3.24000e+02,
       1.22500e+03, 8.41000e+02, 3.48100e+03, 2.50000e+01, 5.76000e+02,
       1.93600e+03, 6.40000e+01, 3.61000e+02, 1.08900e+03, 8.41000e+02,
       4.84000e+02, 9.00000e+02, 1.93600e+03, 6.25000e+02, 5.76000e+02,
       1.36900e+03, 2.91600e+03, 8.41000e+02, 3.84400e+03, 9.00000e+02,
       1.68100e+03, 8.41000e+02, 9.00000e+02, 1.22500e+03, 2.50000e+03,
       9.00000e+00, 2.70400e+03, 1.60000e+03, 1.29600e+03, 2.56000e+02,
       6.25000e+02, 3.36400e+03, 1.22500e+03, 6.25000e+02, 1.68100e+03,
       1.36900e+03, 3.96900e+03, 2.02500e+03, 4.90000e+01, 1.22500e+03,
       4.22500e+03, 7.84000e+02, 2.56000e+02, 3.61000e+02, 1.08900e+03,
       9.00000e+02, 4.84000e+02, 1.76400e+03, 4.84000e+02, 6.76000e+02,
       3.61000e+02, 1.29600e+03, 5.76000e+02, 5.76000e+02, 5.52250e+02,
       4.00000e+00, 2.50000e+03, 3.61000e+02, 8.46400e-01, 2.89000e+02,
       9.00000e+02, 9.00000e+02, 5.76000e+02, 3.24000e+02, 6.76000e+02,
       7.84000e+02, 1.84900e+03, 6.76000e+02, 5.76000e+02, 2.91600e+03,
       9.61000e+02, 1.60000e+03, 4.84000e+02, 7.29000e+02, 9.00000e+02,
       4.84000e+02, 1.29600e+03, 3.72100e+03, 1.29600e+03, 9.61000e+02,
       2.56000e+02, 2.07025e+03, 1.44400e+03, 2.56000e+02, 8.41000e+02,
       1.68100e+03, 2.02500e+03, 2.02500e+03, 4.00000e+00, 5.76000e+02,
       7.84000e+02, 6.25000e+02, 1.29600e+03, 5.76000e+02, 1.60000e+03,
       9.00000e+00, 1.76400e+03, 5.29000e+02, 2.25000e+02, 6.25000e+02,
       7.84000e+02, 4.84000e+02, 1.44400e+03, 1.60000e+03, 8.41000e+02,
       2.02500e+03, 1.22500e+03, 9.00000e+02, 3.60000e+03, 5.76000e+02,
       6.25000e+02, 3.24000e+02, 3.61000e+02, 4.84000e+02, 9.00000e+00,
       4.84000e+02, 7.29000e+02, 4.00000e+02, 3.61000e+02, 1.76400e+03,
       1.00000e+00, 1.02400e+03, 1.22500e+03, 3.24000e+02, 1.00000e+00,
       1.29600e+03, 2.89000e+02, 1.29600e+03, 4.41000e+02, 7.84000e+02,
       5.29000e+02, 5.76000e+02, 4.84000e+02, 9.61000e+02, 2.11600e+03,
       5.29000e+02, 7.84000e+02, 1.52100e+03, 6.76000e+02, 4.41000e+02,
       7.84000e+02, 4.00000e+02, 1.15600e+03, 2.60100e+03, 9.00000e+00,
       4.41000e+02, 1.08900e+03, 1.93600e+03, 1.15600e+03, 3.24000e+02,
       9.00000e+02, 1.00000e+02, 4.41000e+02, 8.41000e+02, 7.84000e+02,
       3.24000e+02, 7.84000e+02, 3.61000e+02, 1.02400e+03, 7.84000e+02,
       1.76400e+03, 2.89000e+02, 2.50000e+03, 1.96000e+02, 4.41000e+02,
       5.76000e+02, 4.09600e+03, 9.61000e+02, 2.02500e+03, 4.00000e+02,
       6.25000e+02, 7.84000e+02, 1.60000e+01, 1.69000e+02, 1.15600e+03,
       2.50000e+01, 2.70400e+03, 1.29600e+03, 9.00000e+02, 2.40100e+03,
       8.41000e+02, 4.22500e+03, 2.50000e+03, 2.30400e+03, 1.15600e+03,
       2.20900e+03, 2.30400e+03, 1.44400e+03, 3.13600e+03, 5.62500e-01,
       1.44400e+03, 1.08900e+03, 5.29000e+02, 4.84000e+02, 1.15600e+03,
       8.41000e+02, 4.84000e+02, 4.00000e+00, 8.10000e+01, 2.50000e+03,
       3.96900e+03, 6.25000e+02, 1.22500e+03, 3.36400e+03, 9.00000e+02,
       8.10000e+01, 4.41000e+02, 3.02500e+03, 5.04100e+03, 4.41000e+02,
       2.91600e+03, 6.25000e+02, 5.76000e+02, 2.89000e+02, 4.41000e+02,
       1.36900e+03, 2.56000e+02, 3.24000e+02, 1.08900e+03, 7.84000e+02,
       6.76000e+02, 8.41000e+02, 1.29600e+03, 2.91600e+03, 5.76000e+02,
       2.20900e+03, 1.15600e+03, 1.29600e+03, 1.02400e+03, 9.00000e+02,
       4.84000e+02, 1.93600e+03, 1.64025e+03, 2.50000e+03, 1.52100e+03,
       5.29000e+02, 4.00000e+00, 2.89000e+02, 9.00000e+02, 4.90000e+01,
       2.02500e+03, 9.00000e+02, 4.84000e+02, 1.29600e+03, 8.10000e+01,
       1.21000e+02, 1.02400e+03, 2.50000e+03, 4.09600e+03, 3.61000e+02,
       1.08900e+03, 6.40000e+01, 2.89000e+02, 7.29000e+02, 4.84000e+02,
       4.84000e+02, 3.84400e+03, 2.30400e+03, 1.52100e+03, 1.29600e+03,
       1.60000e+03, 7.84000e+02, 5.76000e+02, 3.61000e+02, 8.41000e+02,
       1.02400e+03, 3.84400e+03, 2.80900e+03, 1.29600e+03, 2.56000e+02,
       3.61000e+02, 1.15600e+03, 1.52100e+03, 1.02400e+03, 6.25000e+02,
       1.52100e+03, 2.91600e+03, 1.29600e+03, 3.24000e+02, 2.20900e+03,
       3.60000e+03, 4.84000e+02, 1.22500e+03, 2.70400e+03, 2.20900e+03,
       1.36900e+03, 1.29600e+03, 2.40100e+03, 2.40100e+03, 5.76000e+02,
       1.93600e+03, 1.22500e+03, 1.29600e+03, 9.00000e+02, 7.29000e+02,
       4.84000e+02, 1.60000e+03, 1.52100e+03, 1.22500e+03, 5.76000e+02,
       1.15600e+03, 6.76000e+02, 1.60000e+01, 6.76000e+02, 7.29000e+02,
       1.76400e+03, 4.00000e+02, 4.41000e+02, 4.41000e+02, 3.72100e+03,
       3.24900e+03, 4.41000e+02, 6.76000e+02, 6.40000e+03, 2.60100e+03,
       1.02400e+03, 8.10000e+01, 7.84000e+02, 1.02400e+03, 9.61000e+02,
       1.68100e+03, 4.00000e+02, 5.76000e+02, 4.00000e+00, 5.62500e-01,
       2.30400e+03, 3.61000e+02, 3.13600e+03, 5.29000e+02, 3.24000e+02,
       4.41000e+02, 3.24000e+02, 5.76000e+02, 1.02400e+03, 5.29000e+02,
       3.36400e+03, 2.50000e+03, 1.60000e+03, 2.20900e+03, 1.29600e+03,
       4.00000e+02, 1.02400e+03, 6.25000e+02, 1.84900e+03, 1.60000e+03,
       9.61000e+02, 4.90000e+03, 9.61000e+02, 3.24000e+02, 6.00250e+02,
       3.24000e+02, 1.84900e+03, 1.29600e+03, 7.29000e+02, 4.00000e+02,
       1.96000e+02, 3.60000e+03, 6.25000e+02, 1.96000e+02, 3.61000e+02,
       3.24000e+02, 2.25000e+02, 9.61000e+02, 1.60000e+01, 6.25000e+02,
       3.60000e+03, 2.70400e+03, 1.93600e+03, 2.40100e+03, 1.76400e+03,
       3.24000e+02, 1.22500e+03, 3.24000e+02, 6.25000e+02, 6.76000e+02,
       1.52100e+03, 2.02500e+03, 1.76400e+03, 4.84000e+02, 5.76000e+02,
       2.30400e+03, 8.41000e+02, 2.70400e+03, 3.61000e+02, 1.44400e+03,
       7.29000e+02, 1.08900e+03, 3.60000e+01, 2.89000e+02, 1.15600e+03,
       2.50000e+03, 7.29000e+02, 4.00000e+02, 9.00000e+02, 6.25000e+02,
       6.25000e+02, 8.41000e+02, 1.21000e+02, 5.29000e+02, 5.29000e+02,
       8.12250e+02, 2.30400e+03, 1.22500e+03, 1.29600e+03, 4.41000e+02,
       5.76000e+02, 9.61000e+02, 4.90000e+03, 2.56000e+02, 9.00000e+02,
       3.61000e+02, 9.61000e+02, 1.60000e+01, 3.60000e+01, 1.08900e+03,
       5.29000e+02, 2.30400e+03, 4.48900e-01, 7.84000e+02, 3.24000e+02,
       1.15600e+03, 1.08900e+03, 1.68100e+03, 4.00000e+02, 1.29600e+03,
       2.56000e+02, 2.60100e+03, 9.30250e+02, 1.02400e+03, 5.76000e+02,
       2.30400e+03, 3.24900e+03, 2.91600e+03, 3.24000e+02, 2.50000e+01,
       1.84900e+03, 1.69000e+02, 2.89000e+02, 8.41000e+02, 6.25000e+02,
       6.25000e+02, 3.24000e+02, 6.40000e+01, 1.00000e+00, 2.11600e+03,
       2.56000e+02, 6.25000e+02, 1.52100e+03, 2.40100e+03, 9.61000e+02,
       9.00000e+02, 9.00000e+02, 1.15600e+03, 9.61000e+02, 1.21000e+02,
       1.76400e-01, 7.29000e+02, 9.61000e+02, 1.52100e+03, 3.24000e+02,
       1.52100e+03, 1.08900e+03, 6.76000e+02, 1.52100e+03, 1.22500e+03,
       3.60000e+01, 9.30250e+02, 5.29000e+02, 9.61000e+02, 1.84900e+03,
       1.00000e+02, 2.70400e+03, 7.29000e+02, 1.44400e+03, 7.29000e+02,
       4.00000e+00, 1.00000e+00, 3.84400e+03, 2.25000e+02, 6.88900e-01,
       5.29000e+02, 3.24000e+02, 1.52100e+03, 4.41000e+02, 1.02400e+03,
       4.00000e+02, 2.56000e+02, 9.00000e+02, 1.19025e+03, 2.89000e+02,
       1.76400e+03, 1.22500e+03, 7.84000e+02, 1.60000e+01, 5.47600e+03,
       8.10000e+01, 2.56000e+02, 1.93600e+03, 3.24000e+02, 2.02500e+03,
       2.60100e+03, 5.76000e+02, 1.68100e+03, 4.41000e+02, 2.30400e+03,
       5.76000e+02, 1.76400e+03, 7.29000e+02, 9.61000e+02, 1.60000e+01,
       6.76000e+02, 2.20900e+03, 1.08900e+03, 2.20900e+03, 7.84000e+02,
       2.25000e+02, 4.00000e+02, 3.61000e+02, 3.13600e+03, 6.25000e+02,
       1.08900e+03, 4.84000e+02, 7.84000e+02, 6.25000e+02, 1.52100e+03,
       7.29000e+02, 3.61000e+02, 6.76000e+02, 1.02400e+03])

In [36]:

np.sqrt(ages)

array([4.69041576, 6.164414  , 5.09901951, 5.91607978, 5.91607978,
       7.34846923, 1.41421356, 5.19615242, 3.74165739, 2.        ,
       7.61577311, 4.47213595, 6.244998  , 3.74165739, 7.41619849,
       1.41421356, 5.56776436, 5.91607978, 5.83095189, 3.87298335,
       5.29150262, 2.82842712, 6.164414  , 4.35889894, 6.32455532,
       8.1240384 , 5.29150262, 6.4807407 , 4.58257569, 4.24264069,
       3.74165739, 6.32455532, 5.19615242, 1.73205081, 4.35889894,
       4.24264069, 2.64575131, 4.58257569, 7.        , 5.38516481,
       8.06225775, 4.58257569, 5.33853913, 2.23606798, 3.31662479,
       4.69041576, 6.164414  , 6.70820393, 2.        , 5.38516481,
       4.35889894, 4.12310563, 5.09901951, 5.65685425, 4.        ,
       4.58257569, 5.09901951, 5.65685425, 5.        , 0.91104336,
       5.47722558, 4.69041576, 5.38516481, 5.29150262, 4.12310563,
       5.74456265, 4.        , 4.79583152, 4.89897949, 5.38516481,
       4.47213595, 6.78232998, 5.09901951, 7.68114575, 8.42614977,
       4.79583152, 5.83095189, 5.83095189, 5.29150262, 4.58257569,
       5.74456265, 6.08276253, 5.29150262, 4.58257569, 6.164414  ,
       6.8556546 , 3.80788655, 4.69041576, 4.47213595, 4.12310563,
       4.58257569, 8.39642781, 5.38516481, 4.89897949, 1.41421356,
       4.58257569, 5.70087713, 5.70087713, 7.34846923, 3.46410162,
       4.89897949, 6.70820393, 5.74456265, 4.47213595, 6.8556546 ,
       5.38516481, 5.        , 4.79583152, 4.35889894, 6.08276253,
       4.        , 4.89897949, 4.69041576, 4.89897949, 4.35889894,
       4.24264069, 4.35889894, 5.19615242, 3.        , 6.04152299,
       6.4807407 , 7.14142843, 4.69041576, 7.44983221, 6.36396103,
       7.14142843, 4.        , 5.47722558, 6.63324958, 6.32455532,
       5.09901951, 4.12310563, 1.        , 3.        , 6.70820393,
       5.29150262, 7.81024968, 2.        , 1.        , 4.58257569,
       7.48331477, 4.24264069, 7.07106781, 5.47722558, 6.        ,
       3.        , 1.        , 2.        , 6.70820393, 6.32455532,
       6.        , 5.65685425, 4.35889894, 4.35889894, 1.73205081,
       6.63324958, 7.61577311, 6.4807407 , 4.89897949, 5.29150262,
       5.83095189, 6.74536878, 4.24264069, 1.41421356, 5.65685425,
       5.09901951, 4.        , 6.32455532, 4.89897949, 5.91607978,
       4.69041576, 5.47722558, 5.56776436, 5.19615242, 6.4807407 ,
       5.65685425, 5.47722558, 4.        , 5.19615242, 7.14142843,
       6.164414  , 4.69041576, 4.35889894, 4.52769257, 4.24264069,
       5.91607978, 5.38516481, 7.68114575, 2.23606798, 4.89897949,
       6.63324958, 2.82842712, 4.35889894, 5.74456265, 5.38516481,
       4.69041576, 5.47722558, 6.63324958, 5.        , 4.89897949,
       6.08276253, 7.34846923, 5.38516481, 7.87400787, 5.47722558,
       6.40312424, 5.38516481, 5.47722558, 5.91607978, 7.07106781,
       1.73205081, 7.21110255, 6.32455532, 6.        , 4.        ,
       5.        , 7.61577311, 5.91607978, 5.        , 6.40312424,
       6.08276253, 7.93725393, 6.70820393, 2.64575131, 5.91607978,
       8.06225775, 5.29150262, 4.        , 4.35889894, 5.74456265,
       5.47722558, 4.69041576, 6.4807407 , 4.69041576, 5.09901951,
       4.35889894, 6.        , 4.89897949, 4.89897949, 4.84767986,
       1.41421356, 7.07106781, 4.35889894, 0.9591663 , 4.12310563,
       5.47722558, 5.47722558, 4.89897949, 4.24264069, 5.09901951,
       5.29150262, 6.55743852, 5.09901951, 4.89897949, 7.34846923,
       5.56776436, 6.32455532, 4.69041576, 5.19615242, 5.47722558,
       4.69041576, 6.        , 7.81024968, 6.        , 5.56776436,
       4.        , 6.74536878, 6.164414  , 4.        , 5.38516481,
       6.40312424, 6.70820393, 6.70820393, 1.41421356, 4.89897949,
       5.29150262, 5.        , 6.        , 4.89897949, 6.32455532,
       1.73205081, 6.4807407 , 4.79583152, 3.87298335, 5.        ,
       5.29150262, 4.69041576, 6.164414  , 6.32455532, 5.38516481,
       6.70820393, 5.91607978, 5.47722558, 7.74596669, 4.89897949,
       5.        , 4.24264069, 4.35889894, 4.69041576, 1.73205081,
       4.69041576, 5.19615242, 4.47213595, 4.35889894, 6.4807407 ,
       1.        , 5.65685425, 5.91607978, 4.24264069, 1.        ,
       6.        , 4.12310563, 6.        , 4.58257569, 5.29150262,
       4.79583152, 4.89897949, 4.69041576, 5.56776436, 6.78232998,
       4.79583152, 5.29150262, 6.244998  , 5.09901951, 4.58257569,
       5.29150262, 4.47213595, 5.83095189, 7.14142843, 1.73205081,
       4.58257569, 5.74456265, 6.63324958, 5.83095189, 4.24264069,
       5.47722558, 3.16227766, 4.58257569, 5.38516481, 5.29150262,
       4.24264069, 5.29150262, 4.35889894, 5.65685425, 5.29150262,
       6.4807407 , 4.12310563, 7.07106781, 3.74165739, 4.58257569,
       4.89897949, 8.        , 5.56776436, 6.70820393, 4.47213595,
       5.        , 5.29150262, 2.        , 3.60555128, 5.83095189,
       2.23606798, 7.21110255, 6.        , 5.47722558, 7.        ,
       5.38516481, 8.06225775, 7.07106781, 6.92820323, 5.83095189,
       6.8556546 , 6.92820323, 6.164414  , 7.48331477, 0.8660254 ,
       6.164414  , 5.74456265, 4.79583152, 4.69041576, 5.83095189,
       5.38516481, 4.69041576, 1.41421356, 3.        , 7.07106781,
       7.93725393, 5.        , 5.91607978, 7.61577311, 5.47722558,
       3.        , 4.58257569, 7.41619849, 8.42614977, 4.58257569,
       7.34846923, 5.        , 4.89897949, 4.12310563, 4.58257569,
       6.08276253, 4.        , 4.24264069, 5.74456265, 5.29150262,
       5.09901951, 5.38516481, 6.        , 7.34846923, 4.89897949,
       6.8556546 , 5.83095189, 6.        , 5.65685425, 5.47722558,
       4.69041576, 6.63324958, 6.36396103, 7.07106781, 6.244998  ,
       4.79583152, 1.41421356, 4.12310563, 5.47722558, 2.64575131,
       6.70820393, 5.47722558, 4.69041576, 6.        , 3.        ,
       3.31662479, 5.65685425, 7.07106781, 8.        , 4.35889894,
       5.74456265, 2.82842712, 4.12310563, 5.19615242, 4.69041576,
       4.69041576, 7.87400787, 6.92820323, 6.244998  , 6.        ,
       6.32455532, 5.29150262, 4.89897949, 4.35889894, 5.38516481,
       5.65685425, 7.87400787, 7.28010989, 6.        , 4.        ,
       4.35889894, 5.83095189, 6.244998  , 5.65685425, 5.        ,
       6.244998  , 7.34846923, 6.        , 4.24264069, 6.8556546 ,
       7.74596669, 4.69041576, 5.91607978, 7.21110255, 6.8556546 ,
       6.08276253, 6.        , 7.        , 7.        , 4.89897949,
       6.63324958, 5.91607978, 6.        , 5.47722558, 5.19615242,
       4.69041576, 6.32455532, 6.244998  , 5.91607978, 4.89897949,
       5.83095189, 5.09901951, 2.        , 5.09901951, 5.19615242,
       6.4807407 , 4.47213595, 4.58257569, 4.58257569, 7.81024968,
       7.54983444, 4.58257569, 5.09901951, 8.94427191, 7.14142843,
       5.65685425, 3.        , 5.29150262, 5.65685425, 5.56776436,
       6.40312424, 4.47213595, 4.89897949, 1.41421356, 0.8660254 ,
       6.92820323, 4.35889894, 7.48331477, 4.79583152, 4.24264069,
       4.58257569, 4.24264069, 4.89897949, 5.65685425, 4.79583152,
       7.61577311, 7.07106781, 6.32455532, 6.8556546 , 6.        ,
       4.47213595, 5.65685425, 5.        , 6.55743852, 6.32455532,
       5.56776436, 8.36660027, 5.56776436, 4.24264069, 4.94974747,
       4.24264069, 6.55743852, 6.        , 5.19615242, 4.47213595,
       3.74165739, 7.74596669, 5.        , 3.74165739, 4.35889894,
       4.24264069, 3.87298335, 5.56776436, 2.        , 5.        ,
       7.74596669, 7.21110255, 6.63324958, 7.        , 6.4807407 ,
       4.24264069, 5.91607978, 4.24264069, 5.        , 5.09901951,
       6.244998  , 6.70820393, 6.4807407 , 4.69041576, 4.89897949,
       6.92820323, 5.38516481, 7.21110255, 4.35889894, 6.164414  ,
       5.19615242, 5.74456265, 2.44948974, 4.12310563, 5.83095189,
       7.07106781, 5.19615242, 4.47213595, 5.47722558, 5.        ,
       5.        , 5.38516481, 3.31662479, 4.79583152, 4.79583152,
       5.33853913, 6.92820323, 5.91607978, 6.        , 4.58257569,
       4.89897949, 5.56776436, 8.36660027, 4.        , 5.47722558,
       4.35889894, 5.56776436, 2.        , 2.44948974, 5.74456265,
       4.79583152, 6.92820323, 0.81853528, 5.29150262, 4.24264069,
       5.83095189, 5.74456265, 6.40312424, 4.47213595, 6.        ,
       4.        , 7.14142843, 5.52268051, 5.65685425, 4.89897949,
       6.92820323, 7.54983444, 7.34846923, 4.24264069, 2.23606798,
       6.55743852, 3.60555128, 4.12310563, 5.38516481, 5.        ,
       5.        , 4.24264069, 2.82842712, 1.        , 6.78232998,
       4.        , 5.        , 6.244998  , 7.        , 5.56776436,
       5.47722558, 5.47722558, 5.83095189, 5.56776436, 3.31662479,
       0.64807407, 5.19615242, 5.56776436, 6.244998  , 4.24264069,
       6.244998  , 5.74456265, 5.09901951, 6.244998  , 5.91607978,
       2.44948974, 5.52268051, 4.79583152, 5.56776436, 6.55743852,
       3.16227766, 7.21110255, 5.19615242, 6.164414  , 5.19615242,
       1.41421356, 1.        , 7.87400787, 3.87298335, 0.91104336,
       4.79583152, 4.24264069, 6.244998  , 4.58257569, 5.65685425,
       4.47213595, 4.        , 5.47722558, 5.87367006, 4.12310563,
       6.4807407 , 5.91607978, 5.29150262, 2.        , 8.60232527,
       3.        , 4.        , 6.63324958, 4.24264069, 6.70820393,
       7.14142843, 4.89897949, 6.40312424, 4.58257569, 6.92820323,
       4.89897949, 6.4807407 , 5.19615242, 5.56776436, 2.        ,
       5.09901951, 6.8556546 , 5.74456265, 6.8556546 , 5.29150262,
       3.87298335, 4.47213595, 4.35889894, 7.48331477, 5.        ,
       5.74456265, 4.69041576, 5.29150262, 5.        , 6.244998  ,
       5.19615242, 4.35889894, 5.09901951, 5.65685425])

In [37]:
np.abs(ages)

array([22.  , 38.  , 26.  , 35.  , 35.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 31.  , 35.  ,
       34.  , 15.  , 28.  ,  8.  , 38.  , 19.  , 40.  , 66.  , 28.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        7.  , 21.  , 49.  , 29.  , 65.  , 21.  , 28.5 ,  5.  , 11.  ,
       22.  , 38.  , 45.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  ,
       16.  , 21.  , 26.  , 32.  , 25.  ,  0.83, 30.  , 22.  , 29.  ,
       28.  , 17.  , 33.  , 16.  , 23.  , 24.  , 29.  , 20.  , 46.  ,
       26.  , 59.  , 71.  , 23.  , 34.  , 34.  , 28.  , 21.  , 33.  ,
       37.  , 28.  , 21.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  ,
       21.  , 70.5 , 29.  , 24.  ,  2.  , 21.  , 32.5 , 32.5 , 54.  ,
       12.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 , 51.  ,
       16.  , 30.  , 44.  , 40.  , 26.  , 17.  ,  1.  ,  9.  , 45.  ,
       28.  , 61.  ,  4.  ,  1.  , 21.  , 56.  , 18.  , 50.  , 30.  ,
       36.  ,  9.  ,  1.  ,  4.  , 45.  , 40.  , 36.  , 32.  , 19.  ,
       19.  ,  3.  , 44.  , 58.  , 42.  , 24.  , 28.  , 34.  , 45.5 ,
       18.  ,  2.  , 32.  , 26.  , 16.  , 40.  , 24.  , 35.  , 22.  ,
       30.  , 31.  , 27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  ,
       38.  , 22.  , 19.  , 20.5 , 18.  , 35.  , 29.  , 59.  ,  5.  ,
       24.  , 44.  ,  8.  , 19.  , 33.  , 29.  , 22.  , 30.  , 44.  ,
       25.  , 24.  , 37.  , 54.  , 29.  , 62.  , 30.  , 41.  , 29.  ,
       30.  , 35.  , 50.  ,  3.  , 52.  , 40.  , 36.  , 16.  , 25.  ,
       58.  , 35.  , 25.  , 41.  , 37.  , 63.  , 45.  ,  7.  , 35.  ,
       65.  , 28.  , 16.  , 19.  , 33.  , 30.  , 22.  , 42.  , 22.  ,
       26.  , 19.  , 36.  , 24.  , 24.  , 23.5 ,  2.  , 50.  , 19.  ,
        0.92, 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
       36.  , 61.  , 36.  , 31.  , 16.  , 45.5 , 38.  , 16.  , 29.  ,
       41.  , 45.  , 45.  ,  2.  , 24.  , 28.  , 25.  , 36.  , 24.  ,
       40.  ,  3.  , 42.  , 23.  , 15.  , 25.  , 28.  , 22.  , 38.  ,
       40.  , 29.  , 45.  , 35.  , 30.  , 60.  , 24.  , 25.  , 18.  ,
       19.  , 22.  ,  3.  , 22.  , 27.  , 20.  , 19.  , 42.  ,  1.  ,
       32.  , 35.  , 18.  ,  1.  , 36.  , 17.  , 36.  , 21.  , 28.  ,
       23.  , 24.  , 22.  , 31.  , 46.  , 23.  , 28.  , 39.  , 26.  ,
       21.  , 28.  , 20.  , 34.  , 51.  ,  3.  , 21.  , 33.  , 44.  ,
       34.  , 18.  , 30.  , 10.  , 21.  , 29.  , 28.  , 18.  , 28.  ,
       19.  , 32.  , 28.  , 42.  , 17.  , 50.  , 14.  , 21.  , 24.  ,
       64.  , 31.  , 45.  , 20.  , 25.  , 28.  ,  4.  , 13.  , 34.  ,
        5.  , 52.  , 36.  , 30.  , 49.  , 29.  , 65.  , 50.  , 48.  ,
       34.  , 47.  , 48.  , 38.  , 56.  ,  0.75, 38.  , 33.  , 23.  ,
       22.  , 34.  , 29.  , 22.  ,  2.  ,  9.  , 50.  , 63.  , 25.  ,
       35.  , 58.  , 30.  ,  9.  , 21.  , 55.  , 71.  , 21.  , 54.  ,
       25.  , 24.  , 17.  , 21.  , 37.  , 16.  , 18.  , 33.  , 28.  ,
       26.  , 29.  , 36.  , 54.  , 24.  , 47.  , 34.  , 36.  , 32.  ,
       30.  , 22.  , 44.  , 40.5 , 50.  , 39.  , 23.  ,  2.  , 17.  ,
       30.  ,  7.  , 45.  , 30.  , 22.  , 36.  ,  9.  , 11.  , 32.  ,
       50.  , 64.  , 19.  , 33.  ,  8.  , 17.  , 27.  , 22.  , 22.  ,
       62.  , 48.  , 39.  , 36.  , 40.  , 28.  , 24.  , 19.  , 29.  ,
       32.  , 62.  , 53.  , 36.  , 16.  , 19.  , 34.  , 39.  , 32.  ,
       25.  , 39.  , 54.  , 36.  , 18.  , 47.  , 60.  , 22.  , 35.  ,
       52.  , 47.  , 37.  , 36.  , 49.  , 49.  , 24.  , 44.  , 35.  ,
       36.  , 30.  , 27.  , 22.  , 40.  , 39.  , 35.  , 24.  , 34.  ,
       26.  ,  4.  , 26.  , 27.  , 42.  , 20.  , 21.  , 21.  , 61.  ,
       57.  , 21.  , 26.  , 80.  , 51.  , 32.  ,  9.  , 28.  , 32.  ,
       31.  , 41.  , 20.  , 24.  ,  2.  ,  0.75, 48.  , 19.  , 56.  ,
       23.  , 18.  , 21.  , 18.  , 24.  , 32.  , 23.  , 58.  , 50.  ,
       40.  , 47.  , 36.  , 20.  , 32.  , 25.  , 43.  , 40.  , 31.  ,
       70.  , 31.  , 18.  , 24.5 , 18.  , 43.  , 36.  , 27.  , 20.  ,
       14.  , 60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  ,
       25.  , 60.  , 52.  , 44.  , 49.  , 42.  , 18.  , 35.  , 18.  ,
       25.  , 26.  , 39.  , 45.  , 42.  , 22.  , 24.  , 48.  , 29.  ,
       52.  , 19.  , 38.  , 27.  , 33.  ,  6.  , 17.  , 34.  , 50.  ,
       27.  , 20.  , 30.  , 25.  , 25.  , 29.  , 11.  , 23.  , 23.  ,
       28.5 , 48.  , 35.  , 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  , 41.  , 20.  , 36.  , 16.  , 51.  ,
       30.5 , 32.  , 24.  , 48.  , 57.  , 54.  , 18.  ,  5.  , 43.  ,
       13.  , 17.  , 29.  , 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  ,
       16.  , 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  , 31.  ,
       11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  , 26.  ,
       39.  , 35.  ,  6.  , 30.5 , 23.  , 31.  , 43.  , 10.  , 52.  ,
       27.  , 38.  , 27.  ,  2.  ,  1.  , 62.  , 15.  ,  0.83, 23.  ,
       18.  , 39.  , 21.  , 32.  , 20.  , 16.  , 30.  , 34.5 , 17.  ,
       42.  , 35.  , 28.  ,  4.  , 74.  ,  9.  , 16.  , 44.  , 18.  ,
       45.  , 51.  , 24.  , 41.  , 21.  , 48.  , 24.  , 42.  , 27.  ,
       31.  ,  4.  , 26.  , 47.  , 33.  , 47.  , 28.  , 15.  , 20.  ,
       19.  , 56.  , 25.  , 33.  , 22.  , 28.  , 25.  , 39.  , 27.  ,
       19.  , 26.  , 32.  ])

In [39]:
np.sin(ages)

array([-0.00885131,  0.29636858,  0.76255845, -0.42818267, -0.42818267,
       -0.55878905,  0.90929743,  0.95637593,  0.99060736, -0.7568025 ,
        0.99287265,  0.91294525,  0.96379539,  0.99060736, -0.99975517,
        0.90929743, -0.40403765, -0.42818267,  0.52908269,  0.65028784,
        0.27090579,  0.98935825,  0.29636858,  0.14987721,  0.74511316,
       -0.02655115,  0.27090579, -0.91652155,  0.83665564, -0.75098725,
        0.99060736,  0.74511316,  0.95637593,  0.14112001,  0.14987721,
       -0.75098725,  0.6569866 ,  0.83665564, -0.95375265, -0.66363388,
        0.82682868,  0.83665564, -0.22375564, -0.95892427, -0.99999021,
       -0.00885131,  0.29636858,  0.85090352, -0.7568025 , -0.66363388,
        0.14987721, -0.96139749,  0.76255845,  0.55142668, -0.28790332,
        0.83665564,  0.76255845,  0.55142668, -0.13235175,  0.73793137,
       -0.98803162, -0.00885131, -0.66363388,  0.27090579, -0.96139749,
        0.99991186, -0.28790332, -0.8462204 , -0.90557836, -0.66363388,
        0.91294525,  0.90178835,  0.76255845,  0.63673801,  0.95105465,
       -0.8462204 ,  0.52908269,  0.52908269,  0.27090579,  0.83665564,
        0.99991186, -0.64353813,  0.27090579,  0.83665564,  0.29636858,
        0.12357312,  0.93489506, -0.00885131,  0.91294525, -0.96139749,
        0.83665564,  0.98278237, -0.66363388, -0.90557836,  0.90929743,
        0.83665564,  0.88387042,  0.88387042, -0.55878905, -0.53657292,
       -0.90557836,  0.85090352,  0.99991186,  0.91294525,  0.12357312,
       -0.66363388, -0.13235175, -0.8462204 ,  0.14987721, -0.64353813,
       -0.28790332, -0.90557836, -0.00885131, -0.90557836,  0.14987721,
       -0.75098725,  0.14987721,  0.95637593,  0.41211849, -0.93171689,
       -0.91652155,  0.67022918, -0.00885131, -0.86675957,  0.33415118,
        0.67022918, -0.28790332, -0.98803162,  0.01770193,  0.74511316,
        0.76255845, -0.96139749,  0.84147098,  0.41211849,  0.85090352,
        0.27090579, -0.96611777, -0.7568025 ,  0.84147098,  0.83665564,
       -0.521551  , -0.75098725, -0.26237485, -0.98803162, -0.99177885,
        0.41211849,  0.84147098, -0.7568025 ,  0.85090352,  0.74511316,
       -0.99177885,  0.55142668,  0.14987721,  0.14987721,  0.14112001,
        0.01770193,  0.99287265, -0.91652155, -0.90557836,  0.27090579,
        0.52908269,  0.99859087, -0.75098725,  0.90929743,  0.55142668,
        0.76255845, -0.28790332,  0.74511316, -0.90557836, -0.42818267,
       -0.00885131, -0.98803162, -0.40403765,  0.95637593, -0.91652155,
        0.55142668, -0.98803162, -0.28790332,  0.95637593,  0.67022918,
        0.29636858, -0.00885131,  0.14987721,  0.99682979, -0.75098725,
       -0.42818267, -0.66363388,  0.63673801, -0.95892427, -0.90557836,
        0.01770193,  0.98935825,  0.14987721,  0.99991186, -0.66363388,
       -0.00885131, -0.98803162,  0.01770193, -0.13235175, -0.90557836,
       -0.64353813, -0.55878905, -0.66363388, -0.7391807 , -0.98803162,
       -0.15862267, -0.66363388, -0.98803162, -0.42818267, -0.26237485,
        0.14112001,  0.98662759,  0.74511316, -0.99177885, -0.28790332,
       -0.13235175,  0.99287265, -0.42818267, -0.13235175, -0.15862267,
       -0.64353813,  0.1673557 ,  0.85090352,  0.6569866 , -0.42818267,
        0.82682868,  0.27090579, -0.28790332,  0.14987721,  0.99991186,
       -0.98803162, -0.00885131, -0.91652155, -0.00885131,  0.76255845,
        0.14987721, -0.99177885, -0.90557836, -0.90557836, -0.99808203,
        0.90929743, -0.26237485,  0.14987721,  0.79560162, -0.96139749,
       -0.98803162, -0.98803162, -0.90557836, -0.75098725,  0.76255845,
        0.27090579, -0.83177474,  0.76255845, -0.90557836, -0.55878905,
       -0.40403765,  0.74511316, -0.00885131,  0.95637593, -0.98803162,
       -0.00885131, -0.99177885, -0.96611777, -0.99177885, -0.40403765,
       -0.28790332,  0.99859087,  0.29636858, -0.28790332, -0.66363388,
       -0.15862267,  0.85090352,  0.85090352,  0.90929743, -0.90557836,
        0.27090579, -0.13235175, -0.99177885, -0.90557836,  0.74511316,
        0.14112001, -0.91652155, -0.8462204 ,  0.65028784, -0.13235175,
        0.27090579, -0.00885131,  0.29636858,  0.74511316, -0.66363388,
        0.85090352, -0.42818267, -0.98803162, -0.30481062, -0.90557836,
       -0.13235175, -0.75098725,  0.14987721, -0.00885131,  0.14112001,
       -0.00885131,  0.95637593,  0.91294525,  0.14987721, -0.91652155,
        0.84147098,  0.55142668, -0.42818267, -0.75098725,  0.84147098,
       -0.99177885, -0.96139749, -0.99177885,  0.83665564,  0.27090579,
       -0.8462204 , -0.90557836, -0.00885131, -0.40403765,  0.90178835,
       -0.8462204 ,  0.27090579,  0.96379539,  0.76255845,  0.83665564,
        0.27090579,  0.91294525,  0.52908269,  0.67022918,  0.14112001,
        0.83665564,  0.99991186,  0.01770193,  0.52908269, -0.75098725,
       -0.98803162, -0.54402111,  0.83665564, -0.66363388,  0.27090579,
       -0.75098725,  0.27090579,  0.14987721,  0.55142668,  0.27090579,
       -0.91652155, -0.96139749, -0.26237485,  0.99060736,  0.83665564,
       -0.90557836,  0.92002604, -0.40403765,  0.85090352,  0.91294525,
       -0.13235175,  0.27090579, -0.7568025 ,  0.42016704,  0.52908269,
       -0.95892427,  0.98662759, -0.99177885, -0.98803162, -0.95375265,
       -0.66363388,  0.82682868, -0.26237485, -0.76825466,  0.52908269,
        0.12357312, -0.76825466,  0.29636858, -0.521551  ,  0.68163876,
        0.29636858,  0.99991186, -0.8462204 , -0.00885131,  0.52908269,
       -0.66363388, -0.00885131,  0.90929743,  0.41211849, -0.26237485,
        0.1673557 , -0.13235175, -0.42818267,  0.99287265, -0.98803162,
        0.41211849,  0.83665564, -0.99975517,  0.95105465,  0.83665564,
       -0.55878905, -0.13235175, -0.90557836, -0.96139749,  0.83665564,
       -0.64353813, -0.28790332, -0.75098725,  0.99991186,  0.27090579,
        0.76255845, -0.66363388, -0.99177885, -0.55878905, -0.90557836,
        0.12357312,  0.52908269, -0.99177885,  0.55142668, -0.98803162,
       -0.00885131,  0.01770193,  0.33415118, -0.26237485,  0.96379539,
       -0.8462204 ,  0.90929743, -0.96139749, -0.98803162,  0.6569866 ,
        0.85090352, -0.98803162, -0.00885131, -0.99177885,  0.41211849,
       -0.99999021,  0.55142668, -0.26237485,  0.92002604,  0.14987721,
        0.99991186,  0.98935825, -0.96139749,  0.95637593, -0.00885131,
       -0.00885131, -0.7391807 , -0.76825466,  0.96379539, -0.99177885,
        0.74511316,  0.27090579, -0.90557836,  0.14987721, -0.66363388,
        0.55142668, -0.7391807 ,  0.39592515, -0.99177885, -0.28790332,
        0.14987721,  0.52908269,  0.96379539,  0.55142668, -0.13235175,
        0.96379539, -0.55878905, -0.99177885, -0.75098725,  0.12357312,
       -0.30481062, -0.00885131, -0.42818267,  0.98662759,  0.12357312,
       -0.64353813, -0.99177885, -0.95375265, -0.95375265, -0.90557836,
        0.01770193, -0.42818267, -0.99177885, -0.98803162,  0.95637593,
       -0.00885131,  0.74511316,  0.96379539, -0.42818267, -0.90557836,
        0.52908269,  0.76255845, -0.7568025 ,  0.76255845,  0.95637593,
       -0.91652155,  0.91294525,  0.83665564,  0.83665564, -0.96611777,
        0.43616476,  0.83665564,  0.76255845, -0.99388865,  0.67022918,
        0.55142668,  0.41211849,  0.27090579,  0.55142668, -0.40403765,
       -0.15862267,  0.91294525, -0.90557836,  0.90929743,  0.68163876,
       -0.76825466,  0.14987721, -0.521551  , -0.8462204 , -0.75098725,
        0.83665564, -0.75098725, -0.90557836,  0.55142668, -0.8462204 ,
        0.99287265, -0.26237485,  0.74511316,  0.12357312, -0.99177885,
        0.91294525,  0.55142668, -0.13235175, -0.83177474,  0.74511316,
       -0.40403765,  0.77389068, -0.40403765, -0.75098725, -0.59135753,
       -0.75098725, -0.83177474, -0.99177885,  0.95637593,  0.91294525,
        0.99060736, -0.30481062, -0.13235175,  0.99060736,  0.14987721,
       -0.75098725,  0.65028784, -0.40403765, -0.7568025 , -0.13235175,
       -0.30481062,  0.98662759,  0.01770193, -0.95375265, -0.91652155,
       -0.75098725, -0.42818267, -0.75098725, -0.13235175,  0.76255845,
        0.96379539,  0.85090352, -0.91652155, -0.00885131, -0.90557836,
       -0.76825466, -0.66363388,  0.98662759,  0.14987721,  0.29636858,
        0.95637593,  0.99991186, -0.2794155 , -0.96139749,  0.52908269,
       -0.26237485,  0.95637593,  0.91294525, -0.98803162, -0.13235175,
       -0.13235175, -0.66363388, -0.99999021, -0.8462204 , -0.8462204 ,
       -0.22375564, -0.76825466, -0.42818267, -0.99177885,  0.83665564,
       -0.90557836, -0.40403765,  0.77389068, -0.28790332, -0.98803162,
        0.14987721, -0.40403765, -0.7568025 , -0.2794155 ,  0.99991186,
       -0.8462204 , -0.76825466,  0.62098599,  0.27090579, -0.75098725,
        0.52908269,  0.99991186, -0.15862267,  0.91294525, -0.99177885,
       -0.28790332,  0.67022918, -0.79312724,  0.55142668, -0.90557836,
       -0.76825466,  0.43616476, -0.55878905, -0.75098725, -0.95892427,
       -0.83177474,  0.42016704, -0.96139749, -0.66363388, -0.13235175,
       -0.13235175, -0.75098725,  0.98935825,  0.84147098,  0.90178835,
       -0.28790332, -0.13235175,  0.96379539, -0.95375265, -0.40403765,
       -0.98803162, -0.98803162,  0.52908269, -0.40403765, -0.99999021,
        0.40776045,  0.95637593, -0.40403765,  0.96379539, -0.75098725,
        0.96379539,  0.99991186,  0.76255845,  0.96379539, -0.42818267,
       -0.2794155 , -0.79312724, -0.8462204 , -0.40403765, -0.83177474,
       -0.54402111,  0.98662759,  0.95637593,  0.29636858,  0.95637593,
        0.90929743,  0.84147098, -0.7391807 ,  0.65028784,  0.73793137,
       -0.8462204 , -0.75098725,  0.96379539,  0.83665564,  0.55142668,
        0.91294525, -0.28790332, -0.98803162,  0.05748748, -0.96139749,
       -0.91652155, -0.42818267,  0.27090579, -0.7568025 , -0.98514626,
        0.41211849, -0.28790332,  0.01770193, -0.75098725,  0.85090352,
        0.67022918, -0.90557836, -0.15862267,  0.83665564, -0.76825466,
       -0.90557836, -0.91652155,  0.95637593, -0.40403765, -0.7568025 ,
        0.76255845,  0.12357312,  0.99991186,  0.12357312,  0.27090579,
        0.65028784,  0.91294525,  0.14987721, -0.521551  , -0.13235175,
        0.99991186, -0.00885131,  0.27090579, -0.13235175,  0.96379539,
        0.95637593,  0.14987721,  0.76255845,  0.55142668])

In [40]:
np.cos(ages)

array([-0.99996083,  0.95507364,  0.64691932, -0.90369221, -0.90369221,
       -0.82930983, -0.41614684, -0.29213881,  0.13673722, -0.65364362,
        0.11918014,  0.40808206,  0.26664293,  0.13673722,  0.02212676,
       -0.41614684,  0.91474236, -0.90369221, -0.84857027, -0.75968791,
       -0.96260587, -0.14550003,  0.95507364,  0.98870462, -0.66693806,
       -0.99964746, -0.96260587, -0.39998531, -0.54772926,  0.66031671,
        0.13673722, -0.66693806, -0.29213881, -0.9899925 ,  0.98870462,
        0.66031671,  0.75390225, -0.54772926,  0.30059254, -0.74805753,
       -0.56245385, -0.54772926, -0.97464528,  0.28366219,  0.0044257 ,
       -0.99996083,  0.95507364,  0.52532199, -0.65364362, -0.74805753,
        0.98870462, -0.27516334,  0.64691932,  0.83422336, -0.95765948,
       -0.54772926,  0.64691932,  0.83422336,  0.99120281,  0.67487576,
        0.15425145, -0.99996083, -0.74805753, -0.96260587, -0.27516334,
       -0.01327675, -0.95765948, -0.53283302,  0.42417901, -0.74805753,
        0.40808206, -0.43217794,  0.64691932, -0.77108022, -0.30902273,
       -0.53283302, -0.84857027, -0.84857027, -0.96260587, -0.54772926,
       -0.01327675,  0.76541405, -0.96260587, -0.54772926,  0.95507364,
       -0.99233547, -0.35492427, -0.99996083,  0.40808206, -0.27516334,
       -0.54772926,  0.18476693, -0.74805753,  0.42417901, -0.41614684,
       -0.54772926,  0.46773184,  0.46773184, -0.82930983,  0.84385396,
        0.42417901,  0.52532199, -0.01327675,  0.40808206, -0.99233547,
       -0.74805753,  0.99120281, -0.53283302,  0.98870462,  0.76541405,
       -0.95765948,  0.42417901, -0.99996083,  0.42417901,  0.98870462,
        0.66031671,  0.98870462, -0.29213881, -0.91113026,  0.36318541,
       -0.39998531,  0.7421542 , -0.99996083,  0.49872622, -0.94251949,
        0.7421542 , -0.95765948,  0.15425145,  0.99984331, -0.66693806,
        0.64691932, -0.27516334,  0.54030231, -0.91113026,  0.52532199,
       -0.96260587, -0.25810164, -0.65364362,  0.54030231, -0.54772926,
        0.85322011,  0.66031671,  0.96496603,  0.15425145, -0.12796369,
       -0.91113026,  0.54030231, -0.65364362,  0.52532199, -0.66693806,
       -0.12796369,  0.83422336,  0.98870462,  0.98870462, -0.9899925 ,
        0.99984331,  0.11918014, -0.39998531,  0.42417901, -0.96260587,
       -0.84857027,  0.05306854,  0.66031671, -0.41614684,  0.83422336,
        0.64691932, -0.95765948, -0.66693806,  0.42417901, -0.90369221,
       -0.99996083,  0.15425145,  0.91474236, -0.29213881, -0.39998531,
        0.83422336,  0.15425145, -0.95765948, -0.29213881,  0.7421542 ,
        0.95507364, -0.99996083,  0.98870462, -0.07956357,  0.66031671,
       -0.90369221, -0.74805753, -0.77108022,  0.28366219,  0.42417901,
        0.99984331, -0.14550003,  0.98870462, -0.01327675, -0.74805753,
       -0.99996083,  0.15425145,  0.99984331,  0.99120281,  0.42417901,
        0.76541405, -0.82930983, -0.74805753,  0.67350716,  0.15425145,
       -0.98733928, -0.74805753,  0.15425145, -0.90369221,  0.96496603,
       -0.9899925 , -0.16299078, -0.66693806, -0.12796369, -0.95765948,
        0.99120281,  0.11918014, -0.90369221,  0.99120281, -0.98733928,
        0.76541405,  0.98589658,  0.52532199,  0.75390225, -0.90369221,
       -0.56245385, -0.96260587, -0.95765948,  0.98870462, -0.01327675,
        0.15425145, -0.99996083, -0.39998531, -0.99996083,  0.64691932,
        0.98870462, -0.12796369,  0.42417901,  0.42417901, -0.06190529,
       -0.41614684,  0.96496603,  0.98870462,  0.60582016, -0.27516334,
        0.15425145,  0.15425145,  0.42417901,  0.66031671,  0.64691932,
       -0.96260587,  0.5551133 ,  0.64691932,  0.42417901, -0.82930983,
        0.91474236, -0.66693806, -0.99996083, -0.29213881,  0.15425145,
       -0.99996083, -0.12796369, -0.25810164, -0.12796369,  0.91474236,
       -0.95765948,  0.05306854,  0.95507364, -0.95765948, -0.74805753,
       -0.98733928,  0.52532199,  0.52532199, -0.41614684,  0.42417901,
       -0.96260587,  0.99120281, -0.12796369,  0.42417901, -0.66693806,
       -0.9899925 , -0.39998531, -0.53283302, -0.75968791,  0.99120281,
       -0.96260587, -0.99996083,  0.95507364, -0.66693806, -0.74805753,
        0.52532199, -0.90369221,  0.15425145, -0.95241298,  0.42417901,
        0.99120281,  0.66031671,  0.98870462, -0.99996083, -0.9899925 ,
       -0.99996083, -0.29213881,  0.40808206,  0.98870462, -0.39998531,
        0.54030231,  0.83422336, -0.90369221,  0.66031671,  0.54030231,
       -0.12796369, -0.27516334, -0.12796369, -0.54772926, -0.96260587,
       -0.53283302,  0.42417901, -0.99996083,  0.91474236, -0.43217794,
       -0.53283302, -0.96260587,  0.26664293,  0.64691932, -0.54772926,
       -0.96260587,  0.40808206, -0.84857027,  0.7421542 , -0.9899925 ,
       -0.54772926, -0.01327675,  0.99984331, -0.84857027,  0.66031671,
        0.15425145, -0.83907153, -0.54772926, -0.74805753, -0.96260587,
        0.66031671, -0.96260587,  0.98870462,  0.83422336, -0.96260587,
       -0.39998531, -0.27516334,  0.96496603,  0.13673722, -0.54772926,
        0.42417901,  0.39185723,  0.91474236,  0.52532199,  0.40808206,
        0.99120281, -0.96260587, -0.65364362,  0.90744678, -0.84857027,
        0.28366219, -0.16299078, -0.12796369,  0.15425145,  0.30059254,
       -0.74805753, -0.56245385,  0.96496603, -0.64014434, -0.84857027,
       -0.99233547, -0.64014434,  0.95507364,  0.85322011,  0.73168887,
        0.95507364, -0.01327675, -0.53283302, -0.99996083, -0.84857027,
       -0.74805753, -0.99996083, -0.41614684, -0.91113026,  0.96496603,
        0.98589658,  0.99120281, -0.90369221,  0.11918014,  0.15425145,
       -0.91113026, -0.54772926,  0.02212676, -0.30902273, -0.54772926,
       -0.82930983,  0.99120281,  0.42417901, -0.27516334, -0.54772926,
        0.76541405, -0.95765948,  0.66031671, -0.01327675, -0.96260587,
        0.64691932, -0.74805753, -0.12796369, -0.82930983,  0.42417901,
       -0.99233547, -0.84857027, -0.12796369,  0.83422336,  0.15425145,
       -0.99996083,  0.99984331, -0.94251949,  0.96496603,  0.26664293,
       -0.53283302, -0.41614684, -0.27516334,  0.15425145,  0.75390225,
        0.52532199,  0.15425145, -0.99996083, -0.12796369, -0.91113026,
        0.0044257 ,  0.83422336,  0.96496603,  0.39185723,  0.98870462,
       -0.01327675, -0.14550003, -0.27516334, -0.29213881, -0.99996083,
       -0.99996083,  0.67350716, -0.64014434,  0.26664293, -0.12796369,
       -0.66693806, -0.96260587,  0.42417901,  0.98870462, -0.74805753,
        0.83422336,  0.67350716, -0.91828279, -0.12796369, -0.95765948,
        0.98870462, -0.84857027,  0.26664293,  0.83422336,  0.99120281,
        0.26664293, -0.82930983, -0.12796369,  0.66031671, -0.99233547,
       -0.95241298, -0.99996083, -0.90369221, -0.16299078, -0.99233547,
        0.76541405, -0.12796369,  0.30059254,  0.30059254,  0.42417901,
        0.99984331, -0.90369221, -0.12796369,  0.15425145, -0.29213881,
       -0.99996083, -0.66693806,  0.26664293, -0.90369221,  0.42417901,
       -0.84857027,  0.64691932, -0.65364362,  0.64691932, -0.29213881,
       -0.39998531,  0.40808206, -0.54772926, -0.54772926, -0.25810164,
        0.89986683, -0.54772926,  0.64691932, -0.11038724,  0.7421542 ,
        0.83422336, -0.91113026, -0.96260587,  0.83422336,  0.91474236,
       -0.98733928,  0.40808206,  0.42417901, -0.41614684,  0.73168887,
       -0.64014434,  0.98870462,  0.85322011, -0.53283302,  0.66031671,
       -0.54772926,  0.66031671,  0.42417901,  0.83422336, -0.53283302,
        0.11918014,  0.96496603, -0.66693806, -0.99233547, -0.12796369,
        0.40808206,  0.83422336,  0.99120281,  0.5551133 , -0.66693806,
        0.91474236,  0.6333192 ,  0.91474236,  0.66031671,  0.80640949,
        0.66031671,  0.5551133 , -0.12796369, -0.29213881,  0.40808206,
        0.13673722, -0.95241298,  0.99120281,  0.13673722,  0.98870462,
        0.66031671, -0.75968791,  0.91474236, -0.65364362,  0.99120281,
       -0.95241298, -0.16299078,  0.99984331,  0.30059254, -0.39998531,
        0.66031671, -0.90369221,  0.66031671,  0.99120281,  0.64691932,
        0.26664293,  0.52532199, -0.39998531, -0.99996083,  0.42417901,
       -0.64014434, -0.74805753, -0.16299078,  0.98870462,  0.95507364,
       -0.29213881, -0.01327675,  0.96017029, -0.27516334, -0.84857027,
        0.96496603, -0.29213881,  0.40808206,  0.15425145,  0.99120281,
        0.99120281, -0.74805753,  0.0044257 , -0.53283302, -0.53283302,
       -0.97464528, -0.64014434, -0.90369221, -0.12796369, -0.54772926,
        0.42417901,  0.91474236,  0.6333192 , -0.95765948,  0.15425145,
        0.98870462,  0.91474236, -0.65364362,  0.96017029, -0.01327675,
       -0.53283302, -0.64014434,  0.78382167, -0.96260587,  0.66031671,
       -0.84857027, -0.01327675, -0.98733928,  0.40808206, -0.12796369,
       -0.95765948,  0.7421542 ,  0.60905598,  0.83422336,  0.42417901,
       -0.64014434,  0.89986683, -0.82930983,  0.66031671,  0.28366219,
        0.5551133 ,  0.90744678, -0.27516334, -0.74805753,  0.99120281,
        0.99120281,  0.66031671, -0.14550003,  0.54030231, -0.43217794,
       -0.95765948,  0.99120281,  0.26664293,  0.30059254,  0.91474236,
        0.15425145,  0.15425145, -0.84857027,  0.91474236,  0.0044257 ,
        0.91308894, -0.29213881,  0.91474236,  0.26664293,  0.66031671,
        0.26664293, -0.01327675,  0.64691932,  0.26664293, -0.90369221,
        0.96017029,  0.60905598, -0.53283302,  0.91474236,  0.5551133 ,
       -0.83907153, -0.16299078, -0.29213881,  0.95507364, -0.29213881,
       -0.41614684,  0.54030231,  0.67350716, -0.75968791,  0.67487576,
       -0.53283302,  0.66031671,  0.26664293, -0.54772926,  0.83422336,
        0.40808206, -0.95765948,  0.15425145, -0.99834623, -0.27516334,
       -0.39998531, -0.90369221, -0.96260587, -0.65364362,  0.17171734,
       -0.91113026, -0.95765948,  0.99984331,  0.66031671,  0.52532199,
        0.7421542 ,  0.42417901, -0.98733928, -0.54772926, -0.64014434,
        0.42417901, -0.39998531, -0.29213881,  0.91474236, -0.65364362,
        0.64691932, -0.99233547, -0.01327675, -0.99233547, -0.96260587,
       -0.75968791,  0.40808206,  0.98870462,  0.85322011,  0.99120281,
       -0.01327675, -0.99996083, -0.96260587,  0.99120281,  0.26664293,
       -0.29213881,  0.98870462,  0.64691932,  0.83422336])

In [41]:
np.tan(ages)

array([ 8.85165604e-03,  3.10309661e-01,  1.17875355e+00,  4.73814720e-01,
        4.73814720e-01,  6.73800101e-01, -2.18503986e+00, -3.27370380e+00,
        7.24460662e+00,  1.15782128e+00,  8.33085685e+00,  2.23716094e+00,
        3.61455441e+00,  7.24460662e+00, -4.51830879e+01, -2.18503986e+00,
       -4.41695568e-01,  4.73814720e-01, -6.23498963e-01, -8.55993401e-01,
       -2.81429605e-01, -6.79971146e+00,  3.10309661e-01,  1.51589471e-01,
       -1.11721493e+00,  2.65605178e-02, -2.81429605e-01,  2.29138799e+00,
       -1.52749853e+00, -1.13731371e+00,  7.24460662e+00, -1.11721493e+00,
       -3.27370380e+00, -1.42546543e-01,  1.51589471e-01, -1.13731371e+00,
        8.71447983e-01, -1.52749853e+00, -3.17290855e+00,  8.87142844e-01,
       -1.47003826e+00, -1.52749853e+00,  2.29576489e-01, -3.38051501e+00,
       -2.25950846e+02,  8.85165604e-03,  3.10309661e-01,  1.61977519e+00,
        1.15782128e+00,  8.87142844e-01,  1.51589471e-01,  3.49391565e+00,
        1.17875355e+00,  6.61006041e-01,  3.00632242e-01, -1.52749853e+00,
        1.17875355e+00,  6.61006041e-01, -1.33526407e-01,  1.09343292e+00,
       -6.40533120e+00,  8.85165604e-03,  8.87142844e-01, -2.81429605e-01,
        3.49391565e+00, -7.53130148e+01,  3.00632242e-01,  1.58815308e+00,
       -2.13489670e+00,  8.87142844e-01,  2.23716094e+00, -2.08661353e+00,
        1.17875355e+00, -8.25774009e-01, -3.07762040e+00,  1.58815308e+00,
       -6.23498963e-01, -6.23498963e-01, -2.81429605e-01, -1.52749853e+00,
       -7.53130148e+01, -8.40771255e-01, -2.81429605e-01, -1.52749853e+00,
        3.10309661e-01, -1.24527568e-01, -2.63406913e+00,  8.85165604e-03,
        2.23716094e+00,  3.49391565e+00, -1.52749853e+00,  5.31903819e+00,
        8.87142844e-01, -2.13489670e+00, -2.18503986e+00, -1.52749853e+00,
        1.88969479e+00,  1.88969479e+00,  6.73800101e-01, -6.35859929e-01,
       -2.13489670e+00,  1.61977519e+00, -7.53130148e+01,  2.23716094e+00,
       -1.24527568e-01,  8.87142844e-01, -1.33526407e-01,  1.58815308e+00,
        1.51589471e-01, -8.40771255e-01,  3.00632242e-01, -2.13489670e+00,
        8.85165604e-03, -2.13489670e+00,  1.51589471e-01, -1.13731371e+00,
        1.51589471e-01, -3.27370380e+00, -4.52315659e-01, -2.56540287e+00,
        2.29138799e+00,  9.03086149e-01,  8.85165604e-03, -1.73794668e+00,
       -3.54529726e-01,  9.03086149e-01,  3.00632242e-01, -6.40533120e+00,
        1.77046993e-02, -1.11721493e+00,  1.17875355e+00,  3.49391565e+00,
        1.55740772e+00, -4.52315659e-01,  1.61977519e+00, -2.81429605e-01,
        3.74316794e+00,  1.15782128e+00,  1.55740772e+00, -1.52749853e+00,
       -6.11273688e-01, -1.13731371e+00, -2.71900612e-01, -6.40533120e+00,
        7.75047091e+00, -4.52315659e-01,  1.55740772e+00,  1.15782128e+00,
        1.61977519e+00, -1.11721493e+00,  7.75047091e+00,  6.61006041e-01,
        1.51589471e-01,  1.51589471e-01, -1.42546543e-01,  1.77046993e-02,
        8.33085685e+00,  2.29138799e+00, -2.13489670e+00, -2.81429605e-01,
       -6.23498963e-01,  1.88170043e+01, -1.13731371e+00, -2.18503986e+00,
        6.61006041e-01,  1.17875355e+00,  3.00632242e-01, -1.11721493e+00,
       -2.13489670e+00,  4.73814720e-01,  8.85165604e-03, -6.40533120e+00,
       -4.41695568e-01, -3.27370380e+00,  2.29138799e+00,  6.61006041e-01,
       -6.40533120e+00,  3.00632242e-01, -3.27370380e+00,  9.03086149e-01,
        3.10309661e-01,  8.85165604e-03,  1.51589471e-01, -1.25287217e+01,
       -1.13731371e+00,  4.73814720e-01,  8.87142844e-01, -8.25774009e-01,
       -3.38051501e+00, -2.13489670e+00,  1.77046993e-02, -6.79971146e+00,
        1.51589471e-01, -7.53130148e+01,  8.87142844e-01,  8.85165604e-03,
       -6.40533120e+00,  1.77046993e-02, -1.33526407e-01, -2.13489670e+00,
       -8.40771255e-01,  6.73800101e-01,  8.87142844e-01, -1.09750978e+00,
       -6.40533120e+00,  1.60656699e-01,  8.87142844e-01, -6.40533120e+00,
        4.73814720e-01, -2.71900612e-01, -1.42546543e-01, -6.05327238e+00,
       -1.11721493e+00,  7.75047091e+00,  3.00632242e-01, -1.33526407e-01,
        8.33085685e+00,  4.73814720e-01, -1.33526407e-01,  1.60656699e-01,
       -8.40771255e-01,  1.69749752e-01,  1.61977519e+00,  8.71447983e-01,
        4.73814720e-01, -1.47003826e+00, -2.81429605e-01,  3.00632242e-01,
        1.51589471e-01, -7.53130148e+01, -6.40533120e+00,  8.85165604e-03,
        2.29138799e+00,  8.85165604e-03,  1.17875355e+00,  1.51589471e-01,
        7.75047091e+00, -2.13489670e+00, -2.13489670e+00,  1.61227249e+01,
       -2.18503986e+00, -2.71900612e-01,  1.51589471e-01,  1.31326370e+00,
        3.49391565e+00, -6.40533120e+00, -6.40533120e+00, -2.13489670e+00,
       -1.13731371e+00,  1.17875355e+00, -2.81429605e-01, -1.49838734e+00,
        1.17875355e+00, -2.13489670e+00,  6.73800101e-01, -4.41695568e-01,
       -1.11721493e+00,  8.85165604e-03, -3.27370380e+00, -6.40533120e+00,
        8.85165604e-03,  7.75047091e+00,  3.74316794e+00,  7.75047091e+00,
       -4.41695568e-01,  3.00632242e-01,  1.88170043e+01,  3.10309661e-01,
        3.00632242e-01,  8.87142844e-01,  1.60656699e-01,  1.61977519e+00,
        1.61977519e+00, -2.18503986e+00, -2.13489670e+00, -2.81429605e-01,
       -1.33526407e-01,  7.75047091e+00, -2.13489670e+00, -1.11721493e+00,
       -1.42546543e-01,  2.29138799e+00,  1.58815308e+00, -8.55993401e-01,
       -1.33526407e-01, -2.81429605e-01,  8.85165604e-03,  3.10309661e-01,
       -1.11721493e+00,  8.87142844e-01,  1.61977519e+00,  4.73814720e-01,
       -6.40533120e+00,  3.20040389e-01, -2.13489670e+00, -1.33526407e-01,
       -1.13731371e+00,  1.51589471e-01,  8.85165604e-03, -1.42546543e-01,
        8.85165604e-03, -3.27370380e+00,  2.23716094e+00,  1.51589471e-01,
        2.29138799e+00,  1.55740772e+00,  6.61006041e-01,  4.73814720e-01,
       -1.13731371e+00,  1.55740772e+00,  7.75047091e+00,  3.49391565e+00,
        7.75047091e+00, -1.52749853e+00, -2.81429605e-01,  1.58815308e+00,
       -2.13489670e+00,  8.85165604e-03, -4.41695568e-01, -2.08661353e+00,
        1.58815308e+00, -2.81429605e-01,  3.61455441e+00,  1.17875355e+00,
       -1.52749853e+00, -2.81429605e-01,  2.23716094e+00, -6.23498963e-01,
        9.03086149e-01, -1.42546543e-01, -1.52749853e+00, -7.53130148e+01,
        1.77046993e-02, -6.23498963e-01, -1.13731371e+00, -6.40533120e+00,
        6.48360827e-01, -1.52749853e+00,  8.87142844e-01, -2.81429605e-01,
       -1.13731371e+00, -2.81429605e-01,  1.51589471e-01,  6.61006041e-01,
       -2.81429605e-01,  2.29138799e+00,  3.49391565e+00, -2.71900612e-01,
        7.24460662e+00, -1.52749853e+00, -2.13489670e+00,  2.34786031e+00,
       -4.41695568e-01,  1.61977519e+00,  2.23716094e+00, -1.33526407e-01,
       -2.81429605e-01,  1.15782128e+00,  4.63021133e-01, -6.23498963e-01,
       -3.38051501e+00, -6.05327238e+00,  7.75047091e+00, -6.40533120e+00,
       -3.17290855e+00,  8.87142844e-01, -1.47003826e+00, -2.71900612e-01,
        1.20012724e+00, -6.23498963e-01, -1.24527568e-01,  1.20012724e+00,
        3.10309661e-01, -6.11273688e-01,  9.31596460e-01,  3.10309661e-01,
       -7.53130148e+01,  1.58815308e+00,  8.85165604e-03, -6.23498963e-01,
        8.87142844e-01,  8.85165604e-03, -2.18503986e+00, -4.52315659e-01,
       -2.71900612e-01,  1.69749752e-01, -1.33526407e-01,  4.73814720e-01,
        8.33085685e+00, -6.40533120e+00, -4.52315659e-01, -1.52749853e+00,
       -4.51830879e+01, -3.07762040e+00, -1.52749853e+00,  6.73800101e-01,
       -1.33526407e-01, -2.13489670e+00,  3.49391565e+00, -1.52749853e+00,
       -8.40771255e-01,  3.00632242e-01, -1.13731371e+00, -7.53130148e+01,
       -2.81429605e-01,  1.17875355e+00,  8.87142844e-01,  7.75047091e+00,
        6.73800101e-01, -2.13489670e+00, -1.24527568e-01, -6.23498963e-01,
        7.75047091e+00,  6.61006041e-01, -6.40533120e+00,  8.85165604e-03,
        1.77046993e-02, -3.54529726e-01, -2.71900612e-01,  3.61455441e+00,
        1.58815308e+00, -2.18503986e+00,  3.49391565e+00, -6.40533120e+00,
        8.71447983e-01,  1.61977519e+00, -6.40533120e+00,  8.85165604e-03,
        7.75047091e+00, -4.52315659e-01, -2.25950846e+02,  6.61006041e-01,
       -2.71900612e-01,  2.34786031e+00,  1.51589471e-01, -7.53130148e+01,
       -6.79971146e+00,  3.49391565e+00, -3.27370380e+00,  8.85165604e-03,
        8.85165604e-03, -1.09750978e+00,  1.20012724e+00,  3.61455441e+00,
        7.75047091e+00, -1.11721493e+00, -2.81429605e-01, -2.13489670e+00,
        1.51589471e-01,  8.87142844e-01,  6.61006041e-01, -1.09750978e+00,
       -4.31158197e-01,  7.75047091e+00,  3.00632242e-01,  1.51589471e-01,
       -6.23498963e-01,  3.61455441e+00,  6.61006041e-01, -1.33526407e-01,
        3.61455441e+00,  6.73800101e-01,  7.75047091e+00, -1.13731371e+00,
       -1.24527568e-01,  3.20040389e-01,  8.85165604e-03,  4.73814720e-01,
       -6.05327238e+00, -1.24527568e-01, -8.40771255e-01,  7.75047091e+00,
       -3.17290855e+00, -3.17290855e+00, -2.13489670e+00,  1.77046993e-02,
        4.73814720e-01,  7.75047091e+00, -6.40533120e+00, -3.27370380e+00,
        8.85165604e-03, -1.11721493e+00,  3.61455441e+00,  4.73814720e-01,
       -2.13489670e+00, -6.23498963e-01,  1.17875355e+00,  1.15782128e+00,
        1.17875355e+00, -3.27370380e+00,  2.29138799e+00,  2.23716094e+00,
       -1.52749853e+00, -1.52749853e+00,  3.74316794e+00,  4.84699227e-01,
       -1.52749853e+00,  1.17875355e+00,  9.00365495e+00,  9.03086149e-01,
        6.61006041e-01, -4.52315659e-01, -2.81429605e-01,  6.61006041e-01,
       -4.41695568e-01,  1.60656699e-01,  2.23716094e+00, -2.13489670e+00,
       -2.18503986e+00,  9.31596460e-01,  1.20012724e+00,  1.51589471e-01,
       -6.11273688e-01,  1.58815308e+00, -1.13731371e+00, -1.52749853e+00,
       -1.13731371e+00, -2.13489670e+00,  6.61006041e-01,  1.58815308e+00,
        8.33085685e+00, -2.71900612e-01, -1.11721493e+00, -1.24527568e-01,
        7.75047091e+00,  2.23716094e+00,  6.61006041e-01, -1.33526407e-01,
       -1.49838734e+00, -1.11721493e+00, -4.41695568e-01,  1.22195992e+00,
       -4.41695568e-01, -1.13731371e+00, -7.33321637e-01, -1.13731371e+00,
       -1.49838734e+00,  7.75047091e+00, -3.27370380e+00,  2.23716094e+00,
        7.24460662e+00,  3.20040389e-01, -1.33526407e-01,  7.24460662e+00,
        1.51589471e-01, -1.13731371e+00, -8.55993401e-01, -4.41695568e-01,
        1.15782128e+00, -1.33526407e-01,  3.20040389e-01, -6.05327238e+00,
        1.77046993e-02, -3.17290855e+00,  2.29138799e+00, -1.13731371e+00,
        4.73814720e-01, -1.13731371e+00, -1.33526407e-01,  1.17875355e+00,
        3.61455441e+00,  1.61977519e+00,  2.29138799e+00,  8.85165604e-03,
       -2.13489670e+00,  1.20012724e+00,  8.87142844e-01, -6.05327238e+00,
        1.51589471e-01,  3.10309661e-01, -3.27370380e+00, -7.53130148e+01,
       -2.91006191e-01,  3.49391565e+00, -6.23498963e-01, -2.71900612e-01,
       -3.27370380e+00,  2.23716094e+00, -6.40533120e+00, -1.33526407e-01,
       -1.33526407e-01,  8.87142844e-01, -2.25950846e+02,  1.58815308e+00,
        1.58815308e+00,  2.29576489e-01,  1.20012724e+00,  4.73814720e-01,
        7.75047091e+00, -1.52749853e+00, -2.13489670e+00, -4.41695568e-01,
        1.22195992e+00,  3.00632242e-01, -6.40533120e+00,  1.51589471e-01,
       -4.41695568e-01,  1.15782128e+00, -2.91006191e-01, -7.53130148e+01,
        1.58815308e+00,  1.20012724e+00,  7.92254175e-01, -2.81429605e-01,
       -1.13731371e+00, -6.23498963e-01, -7.53130148e+01,  1.60656699e-01,
        2.23716094e+00,  7.75047091e+00,  3.00632242e-01,  9.03086149e-01,
       -1.30222389e+00,  6.61006041e-01, -2.13489670e+00,  1.20012724e+00,
        4.84699227e-01,  6.73800101e-01, -1.13731371e+00, -3.38051501e+00,
       -1.49838734e+00,  4.63021133e-01,  3.49391565e+00,  8.87142844e-01,
       -1.33526407e-01, -1.33526407e-01, -1.13731371e+00, -6.79971146e+00,
        1.55740772e+00, -2.08661353e+00,  3.00632242e-01, -1.33526407e-01,
        3.61455441e+00, -3.17290855e+00, -4.41695568e-01, -6.40533120e+00,
       -6.40533120e+00, -6.23498963e-01, -4.41695568e-01, -2.25950846e+02,
        4.46572546e-01, -3.27370380e+00, -4.41695568e-01,  3.61455441e+00,
       -1.13731371e+00,  3.61455441e+00, -7.53130148e+01,  1.17875355e+00,
        3.61455441e+00,  4.73814720e-01, -2.91006191e-01, -1.30222389e+00,
        1.58815308e+00, -4.41695568e-01, -1.49838734e+00,  6.48360827e-01,
       -6.05327238e+00, -3.27370380e+00,  3.10309661e-01, -3.27370380e+00,
       -2.18503986e+00,  1.55740772e+00, -1.09750978e+00, -8.55993401e-01,
        1.09343292e+00,  1.58815308e+00, -1.13731371e+00,  3.61455441e+00,
       -1.52749853e+00,  6.61006041e-01,  2.23716094e+00,  3.00632242e-01,
       -6.40533120e+00, -5.75827068e-02,  3.49391565e+00,  2.29138799e+00,
        4.73814720e-01, -2.81429605e-01,  1.15782128e+00, -5.73702254e+00,
       -4.52315659e-01,  3.00632242e-01,  1.77046993e-02, -1.13731371e+00,
        1.61977519e+00,  9.03086149e-01, -2.13489670e+00,  1.60656699e-01,
       -1.52749853e+00,  1.20012724e+00, -2.13489670e+00,  2.29138799e+00,
       -3.27370380e+00, -4.41695568e-01,  1.15782128e+00,  1.17875355e+00,
       -1.24527568e-01, -7.53130148e+01, -1.24527568e-01, -2.81429605e-01,
       -8.55993401e-01,  2.23716094e+00,  1.51589471e-01, -6.11273688e-01,
       -1.33526407e-01, -7.53130148e+01,  8.85165604e-03, -2.81429605e-01,
       -1.33526407e-01,  3.61455441e+00, -3.27370380e+00,  1.51589471e-01,
        1.17875355e+00,  6.61006041e-01])

In [42]:
np.prod(ages[:5])

np.float64(26626600.0)

In [47]:
r=np.histogram(fares, bins=10)
print(r)

(array([732, 106,  31,   2,  11,   6,   0,   0,   0,   3]), array([  0.     ,  51.23292, 102.46584, 153.69876, 204.93168, 256.1646 ,
       307.39752, 358.63044, 409.86336, 461.09628, 512.3292 ]))

In [48]:
a=ages+5
print(a)

[27.   43.   31.   40.   40.   59.    7.   32.   19.    9.   63.   25.
 44.   19.   60.    7.   36.   40.   39.   20.   33.   13.   43.   24.
 45.   71.   33.   47.   26.   23.   19.   45.   32.    8.   24.   23.
 12.   26.   54.   34.   70.   26.   33.5  10.   16.   27.   43.   50.
  9.   34.   24.   22.   31.   37.   21.   26.   31.   37.   30.    5.83
 35.   27.   34.   33.   22.   38.   21.   28.   29.   34.   25.   51.
 31.   64.   76.   28.   39.   39.   33.   26.   38.   42.   33.   26.
 43.   52.   19.5  27.   25.   22.   26.   75.5  34.   29.    7.   26.
 37.5  37.5  59.   17.   29.   50.   38.   25.   52.   34.   30.   28.
 24.   42.   21.   29.   27.   29.   24.   23.   24.   32.   14.   41.5
 47.   56.   27.   60.5  45.5  56.   21.   35.   49.   45.   31.   22.
  6.   14.   50.   33.   66.    9.    6.   26.   61.   23.   55.   35.
 41.   14.    6.    9.   50.   45.   41.   37.   24.   24.    8.   49.
 63.   47.   29.   33.   39.   50.5  23.    7.   37.   31.   21.   45.
 29.   40.   27.   35.   36.   32.   47.   37.   35.   21.   32.   56.
 43.   27.   24.   25.5  23.   40.   34.   64.   10.   29.   49.   13.
 24.   38.   34.   27.   35.   49.   30.   29.   42.   59.   34.   67.
 35.   46.   34.   35.   40.   55.    8.   57.   45.   41.   21.   30.
 63.   40.   30.   46.   42.   68.   50.   12.   40.   70.   33.   21.
 24.   38.   35.   27.   47.   27.   31.   24.   41.   29.   29.   28.5
  7.   55.   24.    5.92 22.   35.   35.   29.   23.   31.   33.   48.
 31.   29.   59.   36.   45.   27.   32.   35.   27.   41.   66.   41.
 36.   21.   50.5  43.   21.   34.   46.   50.   50.    7.   29.   33.
 30.   41.   29.   45.    8.   47.   28.   20.   30.   33.   27.   43.
 45.   34.   50.   40.   35.   65.   29.   30.   23.   24.   27.    8.
 27.   32.   25.   24.   47.    6.   37.   40.   23.    6.   41.   22.
 41.   26.   33.   28.   29.   27.   36.   51.   28.   33.   44.   31.
 26.   33.   25.   39.   56.    8.   26.   38.   49.   39.   23.   35.
 15.   26.   34.   33.   23.   33.   24.   37.   33.   47.   22.   55.
 19.   26.   29.   69.   36.   50.   25.   30.   33.    9.   18.   39.
 10.   57.   41.   35.   54.   34.   70.   55.   53.   39.   52.   53.
 43.   61.    5.75 43.   38.   28.   27.   39.   34.   27.    7.   14.
 55.   68.   30.   40.   63.   35.   14.   26.   60.   76.   26.   59.
 30.   29.   22.   26.   42.   21.   23.   38.   33.   31.   34.   41.
 59.   29.   52.   39.   41.   37.   35.   27.   49.   45.5  55.   44.
 28.    7.   22.   35.   12.   50.   35.   27.   41.   14.   16.   37.
 55.   69.   24.   38.   13.   22.   32.   27.   27.   67.   53.   44.
 41.   45.   33.   29.   24.   34.   37.   67.   58.   41.   21.   24.
 39.   44.   37.   30.   44.   59.   41.   23.   52.   65.   27.   40.
 57.   52.   42.   41.   54.   54.   29.   49.   40.   41.   35.   32.
 27.   45.   44.   40.   29.   39.   31.    9.   31.   32.   47.   25.
 26.   26.   66.   62.   26.   31.   85.   56.   37.   14.   33.   37.
 36.   46.   25.   29.    7.    5.75 53.   24.   61.   28.   23.   26.
 23.   29.   37.   28.   63.   55.   45.   52.   41.   25.   37.   30.
 48.   45.   36.   75.   36.   23.   29.5  23.   48.   41.   32.   25.
 19.   65.   30.   19.   24.   23.   20.   36.    9.   30.   65.   57.
 49.   54.   47.   23.   40.   23.   30.   31.   44.   50.   47.   27.
 29.   53.   34.   57.   24.   43.   32.   38.   11.   22.   39.   55.
 32.   25.   35.   30.   30.   34.   16.   28.   28.   33.5  53.   40.
 41.   26.   29.   36.   75.   21.   35.   24.   36.    9.   11.   38.
 28.   53.    5.67 33.   23.   39.   38.   46.   25.   41.   21.   56.
 35.5  37.   29.   53.   62.   59.   23.   10.   48.   18.   22.   34.
 30.   30.   23.   13.    6.   51.   21.   30.   44.   54.   36.   35.
 35.   39.   36.   16.    5.42 32.   36.   44.   23.   44.   38.   31.
 44.   40.   11.   35.5  28.   36.   48.   15.   57.   32.   43.   32.
  7.    6.   67.   20.    5.83 28.   23.   44.   26.   37.   25.   21.
 35.   39.5  22.   47.   40.   33.    9.   79.   14.   21.   49.   23.
 50.   56.   29.   46.   26.   53.   29.   47.   32.   36.    9.   31.
 52.   38.   52.   33.   20.   25.   24.   61.   30.   38.   27.   33.
 30.   44.   32.   24.   31.   37.  ]